/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorVentanaVendedorNegocio;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import src.Articulo;
import src.CentroComercial;
import src.Cliente;
import src.Empleado;
import src.Negocio;

/**
 *
 * @author Acer
 */
public class VentanaVendedorNegocio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    private ControladorVentanaVendedorNegocio controlador;
    private DefaultTableModel modeloArticulosEnVenta;
    private DefaultTableModel modeloArticulosSeparados;
    private String codigo;
    private int cantidad;
    private Negocio negocio;
    private float valorDescuento;
    private Empleado empleado;

    public VentanaVendedorNegocio(Negocio negocio, Empleado empleado) {
        initComponents();
        setLocationRelativeTo(this);
        this.controlador = new ControladorVentanaVendedorNegocio(negocio);
        this.empleado = empleado;
        this.txtValor.setEnabled(false);
        this.modeloArticulosEnVenta = new DefaultTableModel();
        this.modeloArticulosSeparados = new DefaultTableModel();
        this.cantidad = 0;
        this.codigo = txtCodigoArticulo.getText();
        this.negocio = negocio;
        this.valorDescuento = 0;
        this.txtCodigoArticulo.setEnabled(false);
        this.jDateChooserFechaRecogida.setEnabled(false);
        this.jDateChooserFechaInicio.setEnabled(false);
        this.btnSeparado.setEnabled(false);
        limpiarTabla();
        cargar();
        limpiarTablaSepqarados();
        cargarTablaSeparados();
        mouseTablArticulos();
        mouseTablArticulosSeparados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelRegistrar6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCategoria1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArticulosSeparados = new javax.swing.JTable();
        btnEliminarSerparado = new javax.swing.JButton();
        btnEliminarSerparado1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextDescripcion = new javax.swing.JTextArea();
        txtCodigoArticulo = new javax.swing.JTextField();
        checkSeparado = new java.awt.Checkbox();
        jDateChooserFechaRecogida = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserFechaInicio = new com.toedter.calendar.JDateChooser();
        txtValor = new javax.swing.JTextField();
        btnMulta = new javax.swing.JButton();
        btnMulta1 = new javax.swing.JButton();
        btnSeparado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Bienvenido");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Vendedor ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelRegistrar6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelRegistrar6.setForeground(new java.awt.Color(51, 153, 255));
        jLabelRegistrar6.setText("Salir");
        jLabelRegistrar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrar2MouseClicked(evt);
            }
        });

        jLabel9.setText("¿Deseas salir de la cuenta?");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos separados"));

        jLabel5.setText("Filtrar por categoria:");

        jComboBoxCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria", "Accesorios para Vehículos", "Agro", "Alimentos y Bebidas", "Animales y Mascotas", "Antigüedades y Colecciones", "Arte, Papelería y Mercería", "Bebés", "Belleza y Cuidado Personal", "Boletas para Espectáculos", "Cámaras y Accesorios", "Carros, Motos y Otros", "Celulares y Teléfonos", "Computación", "Consolas y Videojuegos", "Construcción", "Deportes y Fitness", "Electrodomésticos", "Electrónica, Audio y Video", "Herramientas", "Hogar y Muebles", "Industrias y Oficinas", "Inmuebles", "Instrumentos Musicales", "Juegos y Juguetes", "Libros, Revistas y Comics", "Música, Películas y Series", "Recuerdos, Piñatería y Fiestas", "Relojes y Joyas", "Ropa y Accesorios", "Salud y Equipamiento Médico", "Servicios", "Otras categorías" }));
        jComboBoxCategoria1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoria1ItemStateChanged(evt);
            }
        });

        jTableArticulosSeparados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Codigo articulo", "Articulo", "Categoria", "Valor", "Cantidad", "Negocio", "Multa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableArticulosSeparados.setToolTipText("");
        jScrollPane2.setViewportView(jTableArticulosSeparados);
        if (jTableArticulosSeparados.getColumnModel().getColumnCount() > 0) {
            jTableArticulosSeparados.getColumnModel().getColumn(0).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(1).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(2).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(3).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(4).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(5).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(6).setResizable(false);
            jTableArticulosSeparados.getColumnModel().getColumn(7).setResizable(false);
        }

        btnEliminarSerparado.setText("Eliminar separado");
        btnEliminarSerparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSerparadoActionPerformed(evt);
            }
        });

        btnEliminarSerparado1.setText("Pagar separado");
        btnEliminarSerparado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSerparado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarSerparado1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarSerparado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarSerparado)
                    .addComponent(btnEliminarSerparado1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos en venta"));

        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo articulo", "Articulo", "Categoria", "Stock", "Negocio", "Valor", "Con descuento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableArticulos.setToolTipText("");
        jScrollPane8.setViewportView(jTableArticulos);
        if (jTableArticulos.getColumnModel().getColumnCount() > 0) {
            jTableArticulos.getColumnModel().getColumn(0).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(1).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(2).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(3).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(4).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(5).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(6).setResizable(false);
        }

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria", "Accesorios para Vehículos", "Agro", "Alimentos y Bebidas", "Animales y Mascotas", "Antigüedades y Colecciones", "Arte, Papelería y Mercería", "Bebés", "Belleza y Cuidado Personal", "Boletas para Espectáculos", "Cámaras y Accesorios", "Carros, Motos y Otros", "Celulares y Teléfonos", "Computación", "Consolas y Videojuegos", "Construcción", "Deportes y Fitness", "Electrodomésticos", "Electrónica, Audio y Video", "Herramientas", "Hogar y Muebles", "Industrias y Oficinas", "Inmuebles", "Instrumentos Musicales", "Juegos y Juguetes", "Libros, Revistas y Comics", "Música, Películas y Series", "Recuerdos, Piñatería y Fiestas", "Relojes y Joyas", "Ropa y Accesorios", "Salud y Equipamiento Médico", "Servicios", "Otras categorías" }));
        jComboBoxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoriaItemStateChanged(evt);
            }
        });

        jLabel1.setText("Filtrar por categoria:");

        jLabel4.setText("Buscar por nombre:");

        txtNombreBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNombreBuscarCaretUpdate(evt);
            }
        });

        jButton1.setText("limpiar busqueda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 195, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Comprar:");

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Comprar Articulo"));

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar2ActionPerformed(evt);
            }
        });

        txtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidad.setText("Cantidad a comprar");
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        txtArticulo.setForeground(new java.awt.Color(153, 153, 153));
        txtArticulo.setText("Articulo");
        txtArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArticuloFocusLost(evt);
            }
        });
        txtArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtArticuloMouseClicked(evt);
            }
        });

        jTextDescripcion.setColumns(20);
        jTextDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        jTextDescripcion.setRows(5);
        jTextDescripcion.setText("Descripcion");
        jScrollPane9.setViewportView(jTextDescripcion);

        txtCodigoArticulo.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoArticulo.setText("Codigo articulo");
        txtCodigoArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoArticuloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArticulo1FocusLost(evt);
            }
        });

        checkSeparado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkSeparado.setLabel("¿Desea realizar separado?");
        checkSeparado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkSeparadoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Fecha de inicio:");

        txtCorreoCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoCliente.setText("Correo de cliente");
        txtCorreoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoClientetxtArticulo1FocusLost(evt);
            }
        });
        txtCorreoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoClientetxtArticulo1MouseClicked(evt);
            }
        });

        jLabel7.setText("Fecha de recogida:");

        txtValor.setForeground(new java.awt.Color(153, 153, 153));
        txtValor.setText("Valor a pagar");
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });

        btnMulta.setText("Colocar multa");
        btnMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultaActionPerformed(evt);
            }
        });

        btnMulta1.setText("Quitar multa");
        btnMulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulta1ActionPerformed(evt);
            }
        });

        btnSeparado.setText("Realizar separado");
        btnSeparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeparadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtValor))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkSeparado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtArticulo)
                            .addComponent(txtCodigoArticulo)
                            .addComponent(txtCorreoCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDateChooserFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDateChooserFechaRecogida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(btnSeparado)
                        .addGap(33, 33, 33))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSeparado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserFechaRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeparado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMulta1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRegistrar6))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelRegistrar6))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaItemStateChanged
        limpiarTabla();
        cargar();
    }//GEN-LAST:event_jComboBoxCategoriaItemStateChanged

    private void txtArticulo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticulo1FocusLost
        if (txtCodigoArticulo.getText().equals("")) {
            txtCodigoArticulo.setText("Codigo articulo");
            txtCodigoArticulo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtArticulo1FocusLost

    private void txtArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArticuloMouseClicked
        if (txtArticulo.getText().equals("Articulo")) {
            txtArticulo.setText("");
            txtArticulo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtArticuloMouseClicked

    private void txtArticuloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticuloFocusLost
        if (txtArticulo.getText().equals("")) {
            txtArticulo.setText("Articulo");
            txtArticulo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtArticuloFocusLost

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        if (txtValor.getText().equals("")) {
            txtValor.setText("Valor a pagar");
            txtValor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtValorFocusLost

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        if (txtValor.getText().equals("Valor a pagar")) {
            txtValor.setText("");
            txtValor.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtValorFocusGained

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        if (txtCantidad.getText().equals("")) {
            txtCantidad.setText("Cantidad a comprar");
            txtCantidad.setForeground(Color.gray);
        }
        if (validarNumeros(txtCantidad.getText())) {
            Articulo arti = controlador.buscarArticulo(codigo);
            txtValor.setText(String.valueOf(negocio.valorTotal(codigo, Integer.parseInt(txtCantidad.getText()))));
        }
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained
        if (txtCantidad.getText().equals("Cantidad a comprar")) {
            txtCantidad.setText("");
            txtCantidad.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCantidadFocusGained

    private void btnComprar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar2ActionPerformed
        if (txtCorreoCliente.getText().isEmpty() || txtCorreoCliente.getText().equals("Correo de cliente")
                || txtCodigoArticulo.getText().equals("") || txtCodigoArticulo.getText().equals("Codigo articulo")
                || txtArticulo.getText().equals("") || txtArticulo.getText().equals("Articulo")
                || txtValor.getText().equals("") || txtValor.getText().equals("Valor a pagar")
                || txtCantidad.getText().equals("") || txtCantidad.getText().equals("Cantidad a comprar")) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona de la tabla el articulo que deseas comprar");
        } else {
            String correo = txtCorreoCliente.getText();
            Cliente cliente = controlador.buscarClientePorUsuario(correo);
            if (cliente.isMulta()) {
                JOptionPane.showMessageDialog(this, "El cliente con correo " + cliente.getCorreo()
                        + " tiene una multa, por lo que no puede comprar hasta que se ponga al dia con sus multas :(");
            } else {
                for (int i = 0; i < CentroComercial.locales.length; i++) {
                    for (int j = 0; j < CentroComercial.locales[i].length; j++) {
                        if (CentroComercial.locales[i][j].getNegocio() != null) {
                            if (CentroComercial.locales[i][j].getNegocio().getNombre().equals(negocio.getNombre())) {
                                codigo = txtCodigoArticulo.getText();
                                cantidad = Integer.parseInt(txtCantidad.getText());
                                if (controlador.realizarCompra(codigo, empleado, cantidad, cliente)) {
                                    JOptionPane.showMessageDialog(this, "El articulo fue comprado correctamente");
                                    cleanTextField();
                                    limpiarTabla();
                                    cargar();
                                    limpiarTablaSepqarados();
                                    cargarTablaSeparados();
                                } else {
                                    JOptionPane.showMessageDialog(this, "El articulo no pudo ser comprado, verifica que pudo haber fallado :(");
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnComprar2ActionPerformed

    private void jLabelRegistrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrar2MouseClicked
        VentanaLogIn ventanaLogIn = new VentanaLogIn();
        ventanaLogIn.reinciarLogIn();
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegistrar2MouseClicked

    private void btnSeparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeparadoActionPerformed
        if (txtCorreoCliente.getText().isEmpty() || txtCorreoCliente.getText().equals("Correo de cliente") || txtCodigoArticulo.getText().equals("") || txtCodigoArticulo.getText().equals("Codigo articulo")
                || txtArticulo.getText().equals("") || txtArticulo.getText().equals("Articulo")
                || txtValor.getText().equals("") || txtValor.getText().equals("Valor a pagar")
                || txtCantidad.getText().equals("") || txtCantidad.getText().equals("Cantidad a comprar")
                || jDateChooserFechaRecogida.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona de la tabla el articulo que deseas separar y rellena los campos");
        } else {
            String correo = txtCorreoCliente.getText();
            Cliente cliente = controlador.buscarClientePorUsuario(correo);
            if (cliente.isMulta()) {
                JOptionPane.showMessageDialog(this, "El cliente con correo " + cliente.getCorreo()
                        + " tiene una multa, por lo que no puede comprar hasta que se ponga al dia con sus multas :(");
            } else {
                for (int i = 0; i < CentroComercial.locales.length; i++) {
                    for (int j = 0; j < CentroComercial.locales[i].length; j++) {
                        if (CentroComercial.locales[i][j].getNegocio() != null) {
                            if (CentroComercial.locales[i][j].getNegocio().getNombre().equals(negocio.getNombre())) {
                                codigo = txtCodigoArticulo.getText();
                                cantidad = Integer.parseInt(txtCantidad.getText());
                                Date date = jDateChooserFechaRecogida.getDate();
                                if (controlador.realizarSeparado(codigo, cantidad, empleado, negocio, cliente, date)) {
                                    JOptionPane.showMessageDialog(this, "El articulo fue separado correctamente");
                                    cleanTextField();
                                    limpiarTabla();
                                    cargar();
                                    limpiarTablaSepqarados();
                                    cargarTablaSeparados();
                                } else {
                                    JOptionPane.showMessageDialog(this, "El articulo no pudo ser separado, verifica que pudo haber fallado :(");
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSeparadoActionPerformed

    private void checkSeparadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkSeparadoItemStateChanged
        if (checkSeparado.getState()) {
            btnComprar.setEnabled(false);
            btnSeparado.setEnabled(true);
            jDateChooserFechaRecogida.setEnabled(true);
        } else {
            btnComprar.setEnabled(true);
            btnSeparado.setEnabled(false);
            jDateChooserFechaRecogida.setDate(null);
            jDateChooserFechaRecogida.setEnabled(false);

        }
    }//GEN-LAST:event_checkSeparadoItemStateChanged

    private void txtCorreoClientetxtArticulo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoClientetxtArticulo1FocusLost
        if (txtCorreoCliente.getText().equals("")) {
            txtCorreoCliente.setText("Correo de cliente");
            txtCorreoCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoClientetxtArticulo1FocusLost

    private void txtCorreoClientetxtArticulo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoClientetxtArticulo1MouseClicked
        if (txtCorreoCliente.getText().equals("Correo de cliente")) {
            txtCorreoCliente.setText("");
            txtCorreoCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCorreoClientetxtArticulo1MouseClicked

    private void txtCodigoArticuloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoArticuloFocusGained
        if (txtCodigoArticulo.getText().equals("Codigo articulo")) {
            txtCodigoArticulo.setText("");
            txtCodigoArticulo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCodigoArticuloFocusGained

    private void txtCorreoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoClienteFocusGained
        if (txtCorreoCliente.getText().equals("")) {
            txtCorreoCliente.setText("Correo de cliente");
            txtCorreoCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoClienteFocusGained

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (validarNumeros(txtCantidad.getText()) && !txtCantidad.getText().isEmpty()) {
                Articulo arti = controlador.buscarArticulo(codigo);
                txtValor.setText(String.valueOf(negocio.valorTotal(codigo, Integer.parseInt(txtCantidad.getText()))));
            } else {
                txtCantidad.setText("0");
            }
        }
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtNombreBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNombreBuscarCaretUpdate

        String nombre = txtNombreBuscar.getText();

        if (nombre.isEmpty()) {
            jTableArticulos.clearSelection();
        } else {
            for (int i = 0; i < jTableArticulos.getRowCount(); i++) {
                if (jTableArticulos.getValueAt(i, 1).equals(nombre)) {
                    jTableArticulos.requestFocus();
                    jTableArticulos.changeSelection(i, 0, false, false);
                }
            }
        }
    }//GEN-LAST:event_txtNombreBuscarCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtNombreBuscar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxCategoria1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoria1ItemStateChanged
        limpiarTabla();
        cargarTablaSeparados();
    }//GEN-LAST:event_jComboBoxCategoria1ItemStateChanged

    private void btnEliminarSerparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSerparadoActionPerformed
        if (txtCodigoArticulo.getText().equals("") || txtCodigoArticulo.getText().equals("Codigo articulo")) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona de la tabla el articulo que deseas eliminar");
        } else {
            String codigo = txtCodigoArticulo.getText();
            int cantidad = Integer.parseInt(txtCantidad.getText());
            Cliente cliente = controlador.buscarClientePorUsuario(txtCorreoCliente.getText());
            controlador.eliminarSeparado(codigo, cantidad, null, cliente);
            JOptionPane.showMessageDialog(this, "El articulo separado fue eliminado");
            cleanTextField();
            limpiarTablaSepqarados();
            cargarTablaSeparados();
        }
    }//GEN-LAST:event_btnEliminarSerparadoActionPerformed

    private void btnMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultaActionPerformed
        if (txtCorreoCliente.getText().isEmpty() || txtCorreoCliente.getText().equals("Correo de cliente")) {
            JOptionPane.showMessageDialog(this, "Para asignar una multa se debe colocar el correo del cliente");
        } else {
            Cliente cliente = controlador.buscarClientePorUsuario(txtCorreoCliente.getText());
            cliente.setMulta(true);
            JOptionPane.showMessageDialog(this, "Cliente con correo: " + cliente.getCorreo() + " se le coloco una multa");
            cleanTextField();
            limpiarTablaSepqarados();
            cargarTablaSeparados();
            CentroComercial.serializarListaPersonas();
        }
    }//GEN-LAST:event_btnMultaActionPerformed

    private void btnMulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulta1ActionPerformed
        if (txtCorreoCliente.getText().isEmpty() || txtCorreoCliente.getText().equals("Correo de cliente")) {
            JOptionPane.showMessageDialog(this, "Para eliminar una multa se debe colocar el correo del cliente");
        } else {
            Cliente cliente = controlador.buscarClientePorUsuario(txtCorreoCliente.getText());
            cliente.setMulta(false);
            JOptionPane.showMessageDialog(this, "Cliente con correo: " + cliente.getCorreo() + " se retiro la multa");
            cleanTextField();
            limpiarTablaSepqarados();
            cargarTablaSeparados();
            CentroComercial.serializarListaPersonas();
        }
    }//GEN-LAST:event_btnMulta1ActionPerformed

    private void btnEliminarSerparado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSerparado1ActionPerformed
        if (txtCodigoArticulo.getText().equals("") || txtCodigoArticulo.getText().equals("Codigo articulo")
                || txtArticulo.getText().equals("") || txtArticulo.getText().equals("Articulo")
                || txtValor.getText().equals("") || txtValor.getText().equals("Valor a pagar")
                || txtCantidad.getText().equals("") || txtCantidad.getText().equals("Cantidad a comprar")) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona de la tabla el articulo que deseas comprar");
        } else {
            Cliente cliente = controlador.buscarClientePorUsuario(txtCorreoCliente.getText());
            int cantiddad = Integer.parseInt(txtCantidad.getText());
            controlador.pagarSeparado(codigo, cantiddad, null, cliente);
            JOptionPane.showMessageDialog(this, "El articulo fue comprado correctamente");
            cleanTextField();
            limpiarTablaSepqarados();
            cargarTablaSeparados();
        }
    }//GEN-LAST:event_btnEliminarSerparado1ActionPerformed

    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9]*");
    }

    public static boolean validarLetras(String datos) {
        return datos.matches("[a-zA-Z]*");
    }

    public void cargar() {
        modeloArticulosEnVenta = (DefaultTableModel) jTableArticulos.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < CentroComercial.locales.length; i++) {
            for (int j = 0; j < CentroComercial.locales[i].length; j++) {
                if (CentroComercial.locales[i][j].getNegocio() != null) {
                    if (CentroComercial.locales[i][j].getNegocio().getArticulos() != null) {
                        for (int k = 0; k < CentroComercial.locales[i][j].getNegocio().getArticulos().Size(); k++) {
                            Articulo arti = (Articulo) CentroComercial.locales[i][j].getNegocio().getArticulos().obtenerDato(k);
                            if (arti.getCantidadProducto() > 0) {
                                if (jComboBoxCategoria.getSelectedIndex() == 0 || arti.getNombreCategoria().equals(jComboBoxCategoria.getSelectedItem())) {
                                    ob[0] = arti.getCodigo();
                                    ob[1] = arti.getNombreProducto();
                                    ob[2] = arti.getNombreCategoria();
                                    ob[3] = arti.getCantidadProducto();
                                    ob[4] = CentroComercial.locales[i][j].getNegocio().getNombre();
                                    ob[5] = arti.getValorDelProducto();
                                    if (arti.getPorcentajeDescuento() > 0) {
                                        ob[6] = arti.calcularDescuento();
                                    } else {
                                        ob[6] = "No hay";
                                    }
                                    modeloArticulosEnVenta.addRow(ob);
                                }
                            }
                        }
                    }
                }
            }
        }
        jTableArticulos.setModel(modeloArticulosEnVenta);
    }

    public void limpiarTabla() {
        for (int i = 0; i < modeloArticulosEnVenta.getRowCount(); i++) {
            modeloArticulosEnVenta.removeRow(i);
            i = i - 1;
        }
    }

    public void cleanTextField() {
        txtCorreoCliente.setText("Correo de cliente");
        txtCorreoCliente.setForeground(Color.gray);
        txtArticulo.setText("Articulo");
        txtArticulo.setForeground(Color.gray);
        txtValor.setText("Valor a pagar");
        txtValor.setForeground(Color.gray);
        jTextDescripcion.setText("Descripcion");
        jTextDescripcion.setForeground(Color.gray);
        txtCantidad.setText("Cantidad a comprar");
        txtCantidad.setForeground(Color.gray);
        checkSeparado.setState(false);
        if (checkSeparado.getState()) {
            btnComprar.setEnabled(false);
            btnSeparado.setEnabled(true);
            jDateChooserFechaRecogida.setEnabled(true);
        } else {
            btnComprar.setEnabled(true);
            btnSeparado.setEnabled(false);
            jDateChooserFechaRecogida.setDate(null);
            jDateChooserFechaRecogida.setEnabled(false);
        }
    }

    public void cargarTablaSeparados() {
        modeloArticulosSeparados = (DefaultTableModel) jTableArticulosSeparados.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < CentroComercial.personas.Size(); i++) {
            if (CentroComercial.personas.obtenerDato(i) instanceof Cliente) {
                Cliente cliente = (Cliente) CentroComercial.personas.obtenerDato(i);
                for (int j = 0; j < cliente.getListaArticulosSeparados().Size(); j++) {
                    Articulo arti = cliente.getListaArticulosSeparados().obtenerDato(j).getProdutosSeparado();
                    if (arti != null && arti.getCantidadProducto() != 0) {
                        ob[0] = cliente.getCorreo();
                        ob[1] = arti.getCodigo();
                        ob[2] = arti.getNombreProducto();
                        ob[3] = arti.getNombreCategoria();
                        ob[4] = arti.getValorDelProducto();
                        ob[5] = arti.getCantidadProducto();
                        ob[6] = cliente.getListaArticulosSeparados().obtenerDato(j).getNegocio().getNombre();
                        if (cliente.isMulta()) {
                            ob[7] = "Si";
                        } else {
                            ob[7] = "No";
                        }
                        modeloArticulosSeparados.addRow(ob);
                    }
                }
            }
        }

        jTableArticulosSeparados.setModel(modeloArticulosSeparados);
    }

    public void limpiarTablaSepqarados() {
        for (int i = 0; i < modeloArticulosSeparados.getRowCount(); i++) {
            modeloArticulosSeparados.removeRow(i);
            i = i - 1;
        }
    }

    public void mouseTablArticulos() {
        jTableArticulos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtCodigoArticulo.setText(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 0).toString());
                    txtCodigoArticulo.setForeground(Color.black);
                    txtArticulo.setText(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 1).toString());
                    txtArticulo.setForeground(Color.black);
                    codigo = txtCodigoArticulo.getText();
                    jTextDescripcion.setText(negocio.buscarArticulo(codigo).getDecripcionProducto());
                    jTextDescripcion.setForeground(Color.black);
                    if (!jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 4).toString().equals("No hay")) {
                        valorDescuento = Float.parseFloat(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 6).toString());
                    }
                }
            }
        });
    }

    public void mouseTablArticulosSeparados() {
        jTableArticulosSeparados.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtCorreoCliente.setText(jTableArticulosSeparados.getValueAt(jTableArticulosSeparados.getSelectedRow(), 0).toString());
                    txtCorreoCliente.setForeground(Color.black);
                    txtCodigoArticulo.setText(jTableArticulosSeparados.getValueAt(jTableArticulosSeparados.getSelectedRow(), 1).toString());
                    txtCodigoArticulo.setForeground(Color.black);
                    txtArticulo.setText(jTableArticulosSeparados.getValueAt(jTableArticulosSeparados.getSelectedRow(), 2).toString());
                    txtArticulo.setForeground(Color.black);
                    codigo = txtCodigoArticulo.getText();
                    txtCantidad.setText(jTableArticulosSeparados.getValueAt(jTableArticulosSeparados.getSelectedRow(), 5).toString());
                    for (int i = 0; i < CentroComercial.personas.Size(); i++) {
                        if (CentroComercial.personas.obtenerDato(i) instanceof Cliente) {
                            Cliente cliente = (Cliente) CentroComercial.personas.obtenerDato(i);
                            for (int j = 0; j < cliente.getListaArticulosSeparados().Size(); j++) {
                                if (cliente.getListaArticulosSeparados().obtenerDato(j).getProdutosSeparado().getCodigo().equals(codigo)) {
                                    jDateChooserFechaInicio.setDate(cliente.getListaArticulosSeparados().obtenerDato(j).getFechaInicio());
                                    jDateChooserFechaRecogida.setDate(cliente.getListaArticulosSeparados().obtenerDato(j).getFechaDeRecogida());
                                }
                            }
                        }
                    }
                    for (int i = 0; i < CentroComercial.locales.length; i++) {
                        for (int j = 0; j < CentroComercial.locales[i].length; j++) {
                            if (CentroComercial.locales[i][j].getNegocio() != null) {
                                if (CentroComercial.locales[i][j].getNegocio().getNombre().equals(jTableArticulosSeparados.getValueAt(jTableArticulosSeparados.getSelectedRow(), 6).toString())) {
                                    negocio = CentroComercial.locales[i][j].getNegocio();
                                    jTextDescripcion.setText(negocio.buscarArticulo(codigo).getDecripcionProducto());
                                    jTextDescripcion.setForeground(Color.black);
                                }
                            }
                        }
                    }
                    if (validarNumeros(txtCantidad.getText())) {
                        txtValor.setText(String.valueOf(negocio.valorTotal(codigo, Integer.parseInt(txtCantidad.getText()))));
                    }
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVendedorNegocio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVendedorNegocio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVendedorNegocio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVendedorNegocio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEliminarSerparado;
    private javax.swing.JButton btnEliminarSerparado1;
    private javax.swing.JButton btnMulta;
    private javax.swing.JButton btnMulta1;
    private javax.swing.JButton btnSeparado;
    private java.awt.Checkbox checkSeparado;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxCategoria1;
    private com.toedter.calendar.JDateChooser jDateChooserFechaInicio;
    private com.toedter.calendar.JDateChooser jDateChooserFechaRecogida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRegistrar6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableArticulos;
    private javax.swing.JTable jTableArticulosSeparados;
    private javax.swing.JTextArea jTextDescripcion;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoArticulo;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
