/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorVentanaAdministrador;
import controlador.ControladorVentanaGestionarConcurso;
import excepciones.ExcepcionConcursoDuplicado;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import src.CentroComercial;
import src.Cliente;
import src.Concurso;
import src.Persona;

/**
 *
 * @author usuario
 */
public class VentanaGestionarConcurso extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaHistorialConcurso;
    private DefaultTableModel modeloTablaConcurso;
    private ControladorVentanaGestionarConcurso controlador;

    /**
     * Creates new form VentanaConcursos
     */
    public VentanaGestionarConcurso() {
        initComponents();
        setLocationRelativeTo(this);
        this.modeloTablaHistorialConcurso = new DefaultTableModel();
        this.modeloTablaConcurso = new DefaultTableModel();
        this.controlador = new ControladorVentanaGestionarConcurso();
        this.txtCodigoConcurso.setEnabled(false);
        limpiarTablaConcurso();
        limpiarTablaConcursoHistorial();
        cargarTablaConcurso();
        cargarTablaConcursoHistorial();
        mouseTableConcurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelRegistrar5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableConcurso = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        btnRegistrarConcurso = new javax.swing.JButton();
        txtPremioConcurso = new javax.swing.JTextField();
        txtValorMinimoConcurso = new javax.swing.JTextField();
        checkConcurso = new java.awt.Checkbox();
        txtNombreConcurso = new javax.swing.JTextField();
        btnModificarConcurso = new javax.swing.JButton();
        btnEliminarConcurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoConcurso = new javax.swing.JTextField();
        btnRegistrarConcurso1 = new javax.swing.JButton();
        jDateChooserConcursoIni = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooserConcursoFin = new com.toedter.calendar.JDateChooser();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableConcursoHistorial = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        txtNombreGanadorConcurso = new javax.swing.JTextField();
        txtCodigoGanadorConcurso = new javax.swing.JTextField();
        txtCedulaGanadorConcurso = new javax.swing.JTextField();
        txtNombrePremioConcurso = new javax.swing.JTextField();
        txtNombreConcurso1 = new javax.swing.JTextField();
        btnRegistrarGanadorDeConcurso = new javax.swing.JButton();
        btnModificarGanadorDeConcurso = new javax.swing.JButton();
        btnEliminarGanadorDeConcurso = new javax.swing.JButton();
        btnRegistrarDatosGanadorDeConcurso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLocales = new javax.swing.JLabel();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelConcursos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        jLabelSolicitudes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("¿Deseas salir de la cuenta?");

        jLabelRegistrar5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelRegistrar5.setForeground(new java.awt.Color(51, 153, 255));
        jLabelRegistrar5.setText("Salir");
        jLabelRegistrar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrar5MouseClicked(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Concursos vigentes"));

        jTableConcurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Premio", "valor minimo", "Fecha inicio", "Fecha fin", "Participantes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableConcurso);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Gestionar concurso"));

        btnRegistrarConcurso.setText("Registrar");
        btnRegistrarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConcursoActionPerformed(evt);
            }
        });

        txtPremioConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtPremioConcurso.setText("Premio concurso");
        txtPremioConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPremioConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPremioConcursoFocusLost(evt);
            }
        });

        txtValorMinimoConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtValorMinimoConcurso.setText("Valor minimo para participar");
        txtValorMinimoConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorMinimoConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorMinimoConcursoFocusLost(evt);
            }
        });

        checkConcurso.setLabel("¿Vigente?");

        txtNombreConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreConcurso.setText("Nombre concurso");
        txtNombreConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreConcursoFocusLost(evt);
            }
        });

        btnModificarConcurso.setText("Modificar");
        btnModificarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarConcursoActionPerformed(evt);
            }
        });

        btnEliminarConcurso.setText("Eliminar");
        btnEliminarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConcursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha inicio:");

        jLabel9.setText("Fecha de finalizacion:");

        txtCodigoConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoConcurso.setText("Codigo concurso");

        btnRegistrarConcurso1.setText("Limpiar datos");
        btnRegistrarConcurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConcurso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCodigoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtNombreConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtPremioConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtValorMinimoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addComponent(jLabel9)
            .addComponent(checkConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(btnRegistrarConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnModificarConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(btnRegistrarConcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnEliminarConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserConcursoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserConcursoFin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtCodigoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtNombreConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtPremioConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtValorMinimoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserConcursoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(jDateChooserConcursoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(checkConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarConcurso)
                    .addComponent(btnModificarConcurso))
                .addGap(7, 7, 7)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarConcurso1)
                    .addComponent(btnEliminarConcurso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial de concursos"));

        jTableConcursoHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Premio", "valor minimo", "Fecha inicio", "Fecha fin", "Participantes", "Ganador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableConcursoHistorial);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion del ganador"));

        txtNombreGanadorConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreGanadorConcurso.setText("Nombre ganador");
        txtNombreGanadorConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreGanadorConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreGanadorConcursoFocusLost(evt);
            }
        });

        txtCodigoGanadorConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoGanadorConcurso.setText("Codigo concurso");
        txtCodigoGanadorConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoGanadorConcursoFocusGained(evt);
            }
        });

        txtCedulaGanadorConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtCedulaGanadorConcurso.setText("Cedula del ganador");
        txtCedulaGanadorConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaGanadorConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaGanadorConcursoFocusLost(evt);
            }
        });

        txtNombrePremioConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtNombrePremioConcurso.setText("Premio concurso");
        txtNombrePremioConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombrePremioConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombrePremioConcursoFocusLost(evt);
            }
        });

        txtNombreConcurso1.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreConcurso1.setText("Usuario ganador");
        txtNombreConcurso1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreConcurso1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreConcurso1FocusLost(evt);
            }
        });

        btnRegistrarGanadorDeConcurso.setText("Registrar");
        btnRegistrarGanadorDeConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGanadorDeConcursoActionPerformed(evt);
            }
        });

        btnModificarGanadorDeConcurso.setText("Modificar");
        btnModificarGanadorDeConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarGanadorDeConcursoActionPerformed(evt);
            }
        });

        btnEliminarGanadorDeConcurso.setText("Eliminar");
        btnEliminarGanadorDeConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGanadorDeConcursoActionPerformed(evt);
            }
        });

        btnRegistrarDatosGanadorDeConcurso.setText("Limpiar datos");
        btnRegistrarDatosGanadorDeConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDatosGanadorDeConcursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombreConcurso1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoGanadorConcurso, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedulaGanadorConcurso)
                    .addComponent(txtNombrePremioConcurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreGanadorConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrarGanadorDeConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarGanadorDeConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarDatosGanadorDeConcurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarGanadorDeConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoGanadorConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePremioConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreGanadorConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCedulaGanadorConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombreConcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarGanadorDeConcurso)
                    .addComponent(btnRegistrarGanadorDeConcurso)
                    .addComponent(btnModificarGanadorDeConcurso)
                    .addComponent(btnRegistrarDatosGanadorDeConcurso))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRegistrar5)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelRegistrar5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ADMINISTRADOR");

        jLabelLocales.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLocales.setForeground(new java.awt.Color(51, 153, 255));
        jLabelLocales.setText("Locales");
        jLabelLocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLocales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLocalesMouseClicked(evt);
            }
        });

        jLabelEmpleados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelEmpleados.setForeground(new java.awt.Color(51, 153, 255));
        jLabelEmpleados.setText("Empleados");
        jLabelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpleadosMouseClicked(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelClientes.setText("Clientes");
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });

        jLabelConcursos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelConcursos.setForeground(new java.awt.Color(51, 153, 255));
        jLabelConcursos.setText("Ventas");
        jLabelConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConcursosMouseClicked(evt);
            }
        });

        jLabelVentas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(51, 153, 255));
        jLabelVentas.setText("Concursos");
        jLabelVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelSolicitudes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSolicitudes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelSolicitudes.setText("Solicitudes");
        jLabelSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSolicitudesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmpleados)
                    .addComponent(jLabelLocales)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelVentas)
                    .addComponent(jLabelConcursos)
                    .addComponent(jLabelSolicitudes))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelLocales)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmpleados)
                .addGap(18, 18, 18)
                .addComponent(jLabelClientes)
                .addGap(18, 18, 18)
                .addComponent(jLabelConcursos)
                .addGap(18, 18, 18)
                .addComponent(jLabelVentas)
                .addGap(18, 18, 18)
                .addComponent(jLabelSolicitudes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegistrar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrar5MouseClicked
        VentanaLogIn ventanaLogIn = new VentanaLogIn();
        ventanaLogIn.reinciarLogIn();
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegistrar5MouseClicked

    private void btnRegistrarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConcursoActionPerformed
        if (txtNombreConcurso.getText().equals("")
                || txtNombreConcurso.getText().equals("Nombre concurso")
                || txtPremioConcurso.getText().equals("Premio concurso")
                || txtPremioConcurso.getText().equals("")
                || txtValorMinimoConcurso.getText().equals("Valor minimo para participar")
                || txtValorMinimoConcurso.getText().equals("")
                || jDateChooserConcursoFin.getDate() == null
                || jDateChooserConcursoIni.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String nombre = txtNombreConcurso.getText();
            String premio = txtPremioConcurso.getText();
            float valorMinimo = Float.parseFloat(txtValorMinimoConcurso.getText());
            Date fechaInicio = jDateChooserConcursoIni.getDate();
            Date fechaFin = jDateChooserConcursoFin.getDate();
            boolean check = checkConcurso.getState();
            Concurso concurso = new Concurso(valorMinimo, check, nombre, premio, fechaInicio, fechaFin);
            try {
                if (controlador.anadirConcurso(concurso)) {
                    JOptionPane.showMessageDialog(this, "Concurso llamado: " + concurso.getNombreConcurso() + " fue registrado correctamente");
                    limpiarTablaConcurso();
                    limpiarTablaConcursoHistorial();
                    cargarTablaConcurso();
                    cargarTablaConcursoHistorial();
                    cleanTextFieldConcurso();
                }
            } catch (ExcepcionConcursoDuplicado ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarConcursoActionPerformed

    private void txtPremioConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPremioConcursoFocusGained
        if (txtPremioConcurso.getText().equals("Premio concurso")) {
            txtPremioConcurso.setText("");
            txtPremioConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPremioConcursoFocusGained

    private void txtPremioConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPremioConcursoFocusLost
        if (txtPremioConcurso.getText().equals("")) {
            txtPremioConcurso.setText("Premio concurso");
            txtPremioConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPremioConcursoFocusLost

    private void txtValorMinimoConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorMinimoConcursoFocusGained
        if (txtValorMinimoConcurso.getText().equals("Valor minimo para participar")) {
            txtValorMinimoConcurso.setText("");
            txtValorMinimoConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtValorMinimoConcursoFocusGained

    private void txtValorMinimoConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorMinimoConcursoFocusLost
        if (txtValorMinimoConcurso.getText().equals("")) {
            txtValorMinimoConcurso.setText("Valor minimo para participar");
            txtValorMinimoConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtValorMinimoConcursoFocusLost

    private void txtNombreConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreConcursoFocusGained
        if (txtNombreConcurso.getText().equals("Nombre concurso")) {
            txtNombreConcurso.setText("");
            txtNombreConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreConcursoFocusGained

    private void txtNombreConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreConcursoFocusLost
        if (txtNombreConcurso.getText().equals("")) {
            txtNombreConcurso.setText("Nombre concurso");
            txtNombreConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreConcursoFocusLost

    private void btnModificarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarConcursoActionPerformed
        if (txtNombreConcurso.getText().equals("")
                || txtNombreConcurso.getText().equals("Nombre concurso")
                || txtPremioConcurso.getText().equals("Premio concurso")
                || txtPremioConcurso.getText().equals("")
                || txtValorMinimoConcurso.getText().equals("Valor minimo para participar")
                || txtValorMinimoConcurso.getText().equals("")
                || jDateChooserConcursoFin.getDate() == null
                || jDateChooserConcursoIni.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String nombre = txtNombreConcurso.getText();
            String premio = txtPremioConcurso.getText();
            float valorMinimo = Float.parseFloat(txtValorMinimoConcurso.getText());
            Date fechaInicio = jDateChooserConcursoIni.getDate();
            Date fechaFin = jDateChooserConcursoFin.getDate();
            boolean check = checkConcurso.getState();
            Concurso concurso = new Concurso(valorMinimo, check, nombre, premio, fechaInicio, fechaFin);
            if (controlador.modificarConcurso(concurso.getCodigo(), concurso)) {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + concurso.getCodigo() + " modificado correctamente.");
                limpiarTablaConcurso();
                cargarTablaConcurso();
                cleanTextFieldConcurso();
            } else {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + concurso.getCodigo() + " no fue modificado.");
            }
        }
    }//GEN-LAST:event_btnModificarConcursoActionPerformed

    private void btnEliminarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConcursoActionPerformed
        if (txtCodigoConcurso.getText().equals("") || txtCodigoConcurso.getText().equals("Codigo concurso")) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona el concurso que deseas eliminar.");
        } else {
            int codigo = Integer.parseInt(txtCodigoConcurso.getText());
            if (controlador.eliminarConcurso(codigo)) {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + codigo + " fue eliminado correctamente.");
                limpiarTablaConcurso();
                cargarTablaConcurso();
                cleanTextFieldConcurso();
            } else {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + codigo + " NO fue eliminado.");
            }
        }
    }//GEN-LAST:event_btnEliminarConcursoActionPerformed

    private void btnRegistrarConcurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConcurso1ActionPerformed
        cleanTextFieldConcurso();
    }//GEN-LAST:event_btnRegistrarConcurso1ActionPerformed

    private void txtNombreGanadorConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreGanadorConcursoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGanadorConcursoFocusGained

    private void txtNombreGanadorConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreGanadorConcursoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGanadorConcursoFocusLost

    private void txtCodigoGanadorConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoGanadorConcursoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoGanadorConcursoFocusGained

    private void txtCedulaGanadorConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaGanadorConcursoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaGanadorConcursoFocusGained

    private void txtCedulaGanadorConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaGanadorConcursoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaGanadorConcursoFocusLost

    private void txtNombrePremioConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrePremioConcursoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePremioConcursoFocusGained

    private void txtNombrePremioConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrePremioConcursoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePremioConcursoFocusLost

    private void txtNombreConcurso1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreConcurso1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConcurso1FocusGained

    private void txtNombreConcurso1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreConcurso1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConcurso1FocusLost

    private void btnRegistrarGanadorDeConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGanadorDeConcursoActionPerformed
        int codigoConcurso = Integer.parseInt(txtCodigoGanadorConcurso.getText());
        String cedulaCliente = txtCedulaGanadorConcurso.getText();
        if (txtCedulaGanadorConcurso.getText().equals("") || txtCedulaGanadorConcurso.getText().equals("Cedula del ganador")
                || txtCodigoGanadorConcurso.getText().equals("") || txtCodigoGanadorConcurso.getText().equals("Codigo concurso")) {
            JOptionPane.showMessageDialog(this, "Rellena los campos de datos");
        } else {
            Persona persona = controlador.buscarPorCedula(cedulaCliente);
            Concurso concurso = controlador.buscarPorConcurso(codigoConcurso);
            if (persona == null) {
                JOptionPane.showMessageDialog(this, "No se encuentra ninguna "
                        + "persona con la cedula: " + cedulaCliente + " "
                        + "registrado en el sistema");
            } else {
                if (persona instanceof Cliente) {
                    Cliente cliente = (Cliente) persona;
                    if (concurso == null) {
                        JOptionPane.showMessageDialog(this, "No se encuentra ningun "
                                + "concurso con el codigo: " + codigoConcurso + " "
                                + "registrado en el sistema");
                    } else {
                        concurso.setGanador(cliente);
                        JOptionPane.showMessageDialog(this, "El cliente: " + cliente.getNombre() + " "
                                + "es el ganador del concurso de un/una: " + concurso.getPremioConcurso());
                        limpiarTablaConcursoHistorial();
                        cargarTablaConcursoHistorial();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La persona con la "
                            + "cedula: " + cedulaCliente + " no esta registrado "
                            + "como cliente en el sistema");
                }
            }
        }
    }//GEN-LAST:event_btnRegistrarGanadorDeConcursoActionPerformed

    private void btnModificarGanadorDeConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarGanadorDeConcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarGanadorDeConcursoActionPerformed

    private void btnEliminarGanadorDeConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGanadorDeConcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarGanadorDeConcursoActionPerformed

    private void btnRegistrarDatosGanadorDeConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDatosGanadorDeConcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarDatosGanadorDeConcursoActionPerformed

    private void jLabelLocalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLocalesMouseClicked
        VentanaAdministrador ventanaAdministrador = new VentanaAdministrador();
        ventanaAdministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelLocalesMouseClicked

    private void jLabelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpleadosMouseClicked
        VentanaGestionarEmpleadoCentroComercial ventanaRegistroEmpleados = new VentanaGestionarEmpleadoCentroComercial();
        ventanaRegistroEmpleados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEmpleadosMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        VentanaGestionarCliente ventanaGestionarCliente = new VentanaGestionarCliente();
        ventanaGestionarCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConcursosMouseClicked
        VentanaVentasGeneradas ventanaVentasGeneradas = new VentanaVentasGeneradas();
        ventanaVentasGeneradas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelConcursosMouseClicked

    private void jLabelSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSolicitudesMouseClicked
        VentanaGestionarSolicitudes ventanaGestionarSolicitudes = new VentanaGestionarSolicitudes();
        ventanaGestionarSolicitudes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSolicitudesMouseClicked
    public void cargarTablaConcurso() {
        modeloTablaConcurso = (DefaultTableModel) jTableConcurso.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < CentroComercial.concursos.Size(); i++) {
            if (CentroComercial.concursos.obtenerDato(i).isEstado()) {
                ob[0] = CentroComercial.concursos.obtenerDato(i).getCodigo();
                ob[1] = CentroComercial.concursos.obtenerDato(i).getNombreConcurso();
                ob[2] = CentroComercial.concursos.obtenerDato(i).getPremioConcurso();
                ob[3] = CentroComercial.concursos.obtenerDato(i).getValorMinimo();
                ob[4] = CentroComercial.concursos.obtenerDato(i).getFechaIncioConcurso();
                ob[5] = CentroComercial.concursos.obtenerDato(i).getFechaFinConcurso();
                ob[6] = CentroComercial.concursos.obtenerDato(i).getParticipantes().Size();
                modeloTablaConcurso.addRow(ob);
            }
        }
        jTableConcurso.setModel(modeloTablaConcurso);
    }

    public void limpiarTablaConcurso() {
        for (int i = 0; i < modeloTablaConcurso.getRowCount(); i++) {
            modeloTablaConcurso.removeRow(i);
            i = i - 1;
        }
    }

    public void cargarTablaConcursoHistorial() {
        modeloTablaHistorialConcurso = (DefaultTableModel) jTableConcursoHistorial.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < CentroComercial.historialConcursos.getConcursos().Size(); i++) {
            if (CentroComercial.historialConcursos.getConcursos().obtenerDato(i).isEstado()) {
                ob[0] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getCodigo();
                ob[1] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getNombreConcurso();
                ob[2] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getPremioConcurso();
                ob[3] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getValorMinimo();
                ob[4] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getFechaIncioConcurso();
                ob[5] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getFechaFinConcurso();
                ob[6] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getParticipantes().Size();
                if (CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getGanador() == null) {
                    ob[7] = "";
                } else {
                    ob[7] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getGanador().getNombre();
                }
                modeloTablaHistorialConcurso.addRow(ob);
            }
        }
        jTableConcursoHistorial.setModel(modeloTablaHistorialConcurso);
    }

    public void limpiarTablaConcursoHistorial() {
        for (int i = 0; i < modeloTablaHistorialConcurso.getRowCount(); i++) {
            modeloTablaHistorialConcurso.removeRow(i);
            i = i - 1;
        }
    }

    public void cleanTextFieldConcurso() {
        txtCodigoConcurso.setText("Codigo concurso");
        txtCodigoConcurso.setForeground(Color.gray);
        txtNombreConcurso.setText("Nombre concurso");
        txtNombreConcurso.setForeground(Color.gray);
        txtValorMinimoConcurso.setText("Valor minimo para participar");
        txtValorMinimoConcurso.setForeground(Color.gray);
        txtPremioConcurso.setText("Premio concurso");
        txtPremioConcurso.setForeground(Color.gray);
        jDateChooserConcursoIni.setDate(null);
        jDateChooserConcursoFin.setDate(null);
        checkConcurso.setState(false);
    }

    public void mouseTableConcurso() {
        jTableConcurso.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtCodigoConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 0).toString());
                    txtCodigoConcurso.setForeground(Color.black);
                    txtNombreConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 1).toString());
                    txtNombreConcurso.setForeground(Color.black);
                    txtPremioConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 2).toString());
                    txtPremioConcurso.setForeground(Color.black);
                    txtValorMinimoConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 3).toString());
                    txtValorMinimoConcurso.setForeground(Color.black);
                    Concurso concurso = controlador.buscarPorConcurso(Integer.parseInt(txtCodigoConcurso.getText()));
                    jDateChooserConcursoIni.setDate(concurso.getFechaIncioConcurso());
                    jDateChooserConcursoFin.setDate(concurso.getFechaFinConcurso());
                    checkConcurso.setState(concurso.isEstado());
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionarConcurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarConcurso;
    private javax.swing.JButton btnEliminarGanadorDeConcurso;
    private javax.swing.JButton btnModificarConcurso;
    private javax.swing.JButton btnModificarGanadorDeConcurso;
    private javax.swing.JButton btnRegistrarConcurso;
    private javax.swing.JButton btnRegistrarConcurso1;
    private javax.swing.JButton btnRegistrarDatosGanadorDeConcurso;
    private javax.swing.JButton btnRegistrarGanadorDeConcurso;
    private java.awt.Checkbox checkConcurso;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooserConcursoFin;
    private com.toedter.calendar.JDateChooser jDateChooserConcursoIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelConcursos;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelLocales;
    private javax.swing.JLabel jLabelRegistrar5;
    private javax.swing.JLabel jLabelSolicitudes;
    private javax.swing.JLabel jLabelVentas;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableConcurso;
    private javax.swing.JTable jTableConcursoHistorial;
    private javax.swing.JTextField txtCedulaGanadorConcurso;
    private javax.swing.JTextField txtCodigoConcurso;
    private javax.swing.JTextField txtCodigoGanadorConcurso;
    private javax.swing.JTextField txtNombreConcurso;
    private javax.swing.JTextField txtNombreConcurso1;
    private javax.swing.JTextField txtNombreGanadorConcurso;
    private javax.swing.JTextField txtNombrePremioConcurso;
    private javax.swing.JTextField txtPremioConcurso;
    private javax.swing.JTextField txtValorMinimoConcurso;
    // End of variables declaration//GEN-END:variables
}
