/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorVentanaGestionarCliente;
import excepciones.ExcepcionClienteDuplicado;
import excepciones.ExcepcionCorreoDuplicado;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import src.CentroComercial;
import src.Cliente;
import src.Vehiculo;
import static ventana.VentanaSignUp.validarLetras;

/**
 *
 * @author usuario
 */
public class VentanaGestionarCliente extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaCliente;
    private ControladorVentanaGestionarCliente controlador;

    /**
     * Creates new form VentanaGestionarCliente
     */
    public VentanaGestionarCliente() {
        initComponents();
        setLocationRelativeTo(this);
        this.modeloTablaCliente = new DefaultTableModel();
        this.controlador = new ControladorVentanaGestionarCliente();
        this.txtTipoDeVehiculoCliente.setEnabled(false);
        this.txtPlacaVehiculoCliente.setEnabled(false);
        limpiarTablaCliente();
        cargarCliente();
        mouseTableCliente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLocales = new javax.swing.JLabel();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelConcursos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        jLabelSolicitudes = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelRegistrar3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnRegistrarCliente = new javax.swing.JButton();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtEdadCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        txtContrasenaCliente = new javax.swing.JPasswordField();
        checkVehiculoCliente = new java.awt.Checkbox();
        txtPlacaVehiculoCliente = new javax.swing.JTextField();
        txtTipoDeVehiculoCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ADMINISTRADOR");

        jLabelLocales.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLocales.setForeground(new java.awt.Color(51, 153, 255));
        jLabelLocales.setText("Locales");
        jLabelLocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLocales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLocalesMouseClicked(evt);
            }
        });

        jLabelEmpleados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelEmpleados.setForeground(new java.awt.Color(51, 153, 255));
        jLabelEmpleados.setText("Empleados");
        jLabelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpleadosMouseClicked(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClientes.setText("Clientes");
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelConcursos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelConcursos.setForeground(new java.awt.Color(51, 153, 255));
        jLabelConcursos.setText("Ventas");
        jLabelConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConcursosMouseClicked(evt);
            }
        });

        jLabelVentas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(51, 153, 255));
        jLabelVentas.setText("Concursos");
        jLabelVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentasMouseClicked(evt);
            }
        });

        jLabelSolicitudes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSolicitudes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelSolicitudes.setText("Solicitudes");
        jLabelSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSolicitudesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmpleados)
                    .addComponent(jLabelLocales)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelVentas)
                    .addComponent(jLabelConcursos)
                    .addComponent(jLabelSolicitudes))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelLocales)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmpleados)
                .addGap(18, 18, 18)
                .addComponent(jLabelClientes)
                .addGap(18, 18, 18)
                .addComponent(jLabelConcursos)
                .addGap(18, 18, 18)
                .addComponent(jLabelVentas)
                .addGap(18, 18, 18)
                .addComponent(jLabelSolicitudes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("¿Deseas salir de la cuenta?");

        jLabelRegistrar3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelRegistrar3.setForeground(new java.awt.Color(51, 153, 255));
        jLabelRegistrar3.setText("Salir");
        jLabelRegistrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrar3MouseClicked(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Gestionar cliente"));

        btnRegistrarCliente.setText("Registrar");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        txtTelefonoCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoCliente.setText("Numero movil");
        txtTelefonoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoClienteFocusLost(evt);
            }
        });

        txtEdadCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtEdadCliente.setText("Edad");
        txtEdadCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEdadClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadClienteFocusLost(evt);
            }
        });

        txtCedulaCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCedulaCliente.setText("Cedula");
        txtCedulaCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaClienteFocusLost(evt);
            }
        });

        txtCorreoCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoCliente.setText("Correo");
        txtCorreoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoClienteFocusLost(evt);
            }
        });

        txtContrasenaCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtContrasenaCliente.setText("******");
        txtContrasenaCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaClienteFocusLost(evt);
            }
        });

        checkVehiculoCliente.setLabel("¿Tiene Vehiculo?");
        checkVehiculoCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkVehiculoClienteItemStateChanged(evt);
            }
        });

        txtPlacaVehiculoCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtPlacaVehiculoCliente.setText("Placa del vehiculo");
        txtPlacaVehiculoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacaVehiculoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaVehiculoClienteFocusLost(evt);
            }
        });

        txtTipoDeVehiculoCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtTipoDeVehiculoCliente.setText("Tipo de vehiculo");
        txtTipoDeVehiculoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoDeVehiculoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoDeVehiculoClienteFocusLost(evt);
            }
        });

        txtNombreCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreCliente.setText("Nombre completo");
        txtNombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreClienteFocusLost(evt);
            }
        });
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreClienteMouseClicked(evt);
            }
        });

        btnModificarCliente.setText("Modificar");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(txtPlacaVehiculoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addComponent(txtTipoDeVehiculoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtEdadCliente, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtContrasenaCliente, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtCorreoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.Alignment.LEADING))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addComponent(checkVehiculoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(txtNombreCliente))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkVehiculoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoDeVehiculoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlacaVehiculoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCliente)
                    .addComponent(btnModificarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarCliente)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes registrados"));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Cedula", "Edad", "Multa", "Tiene vehiculo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setResizable(false);
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            jTableClientes.getColumnModel().getColumn(2).setResizable(false);
            jTableClientes.getColumnModel().getColumn(3).setResizable(false);
            jTableClientes.getColumnModel().getColumn(4).setResizable(false);
            jTableClientes.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRegistrar3)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelRegistrar3))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLocalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLocalesMouseClicked
        VentanaAdministrador ventanaAdministrador = new VentanaAdministrador();
        ventanaAdministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelLocalesMouseClicked

    private void jLabelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpleadosMouseClicked
        VentanaGestionarEmpleadoCentroComercial ventanaRegistroEmpleados = new VentanaGestionarEmpleadoCentroComercial();
        ventanaRegistroEmpleados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEmpleadosMouseClicked

    private void jLabelConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConcursosMouseClicked
        VentanaVentasGeneradas ventanaVentasGeneradas = new VentanaVentasGeneradas();
        ventanaVentasGeneradas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelConcursosMouseClicked

    private void jLabelVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentasMouseClicked
        VentanaGestionarConcurso ventanaGestionarConcurso = new VentanaGestionarConcurso();
        ventanaGestionarConcurso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelVentasMouseClicked

    private void jLabelSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSolicitudesMouseClicked
        VentanaGestionarSolicitudes ventanaGestionarSolicitudes = new VentanaGestionarSolicitudes();
        ventanaGestionarSolicitudes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSolicitudesMouseClicked

    private void jLabelRegistrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrar3MouseClicked
        VentanaLogIn ventanaLogIn = new VentanaLogIn();
        ventanaLogIn.reinciarLogIn();
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegistrar3MouseClicked

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        if (txtCorreoCliente.getText().equals("") || txtCorreoCliente.getText().equals("Correo")
                || String.valueOf(txtContrasenaCliente.getPassword()).equals("")
                || String.valueOf(txtContrasenaCliente.getPassword()).equals("******")
                || txtCedulaCliente.getText().equals("") || txtCedulaCliente.getText().equals("Cedula")
                || txtEdadCliente.getText().equals("") || txtEdadCliente.getText().equals("Edad")
                || txtNombreCliente.getText().equals("") || txtNombreCliente.getText().equals("Nombre completo")
                || txtTelefonoCliente.getText().equals("") || txtTelefonoCliente.getText().equals("Numero movil")) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String telefono = txtTelefonoCliente.getText();
            String nombre = txtNombreCliente.getText();
            short edad = Short.parseShort(txtEdadCliente.getText());
            String cedula = txtCedulaCliente.getText();
            String correo = txtCorreoCliente.getText();
            String contrasena = String.valueOf(txtContrasenaCliente.getPassword());
            Vehiculo vehiculo = vehiculo1();
            Cliente cliente = new Cliente(vehiculo, nombre, cedula, telefono, correo, contrasena, edad);
            try {
                if (controlador.anadirCliente(cliente)) {
                    JOptionPane.showMessageDialog(this, "Registrado correctamente");
                    limpiarTablaCliente();
                    cargarCliente();
                    cleanTextFieldCliente();
                }
            } catch (ExcepcionClienteDuplicado | ExcepcionCorreoDuplicado ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void txtTelefonoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoClienteFocusGained
        if (txtTelefonoCliente.getText().equals("Numero movil")) {
            txtTelefonoCliente.setText("");
            txtTelefonoCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoClienteFocusGained

    private void txtTelefonoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoClienteFocusLost
        if (txtTelefonoCliente.getText().equals("")) {
            txtTelefonoCliente.setText("Numero movil");
            txtTelefonoCliente.setForeground(Color.gray);
        }
        if (!validarNumeros(txtTelefonoCliente.getText()) && !txtTelefonoCliente.getText().equals("Numero movil")) {
            txtTelefonoCliente.setBackground(Color.red);
        } else {
            txtTelefonoCliente.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtTelefonoClienteFocusLost

    private void txtEdadClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadClienteFocusGained
        if (txtEdadCliente.getText().equals("Edad")) {
            txtEdadCliente.setText("");
            txtEdadCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEdadClienteFocusGained

    private void txtEdadClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadClienteFocusLost
        if (txtEdadCliente.getText().equals("")) {
            txtEdadCliente.setText("Edad");
            txtEdadCliente.setForeground(Color.gray);
        }
        if (!validarNumeros(txtEdadCliente.getText()) && !txtEdadCliente.getText().equals("Edad")) {
            txtEdadCliente.setBackground(Color.red);
        } else {
            txtEdadCliente.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtEdadClienteFocusLost

    private void txtCedulaClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaClienteFocusGained
        if (txtCedulaCliente.getText().equals("Cedula")) {
            txtCedulaCliente.setText("");
            txtCedulaCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCedulaClienteFocusGained

    private void txtCedulaClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaClienteFocusLost
        if (txtCedulaCliente.getText().equals("")) {
            txtCedulaCliente.setText("Cedula");
            txtCedulaCliente.setForeground(Color.gray);
        }
        if (!validarNumeros(txtCedulaCliente.getText()) && !txtCedulaCliente.getText().equals("Cedula")) {
            txtCedulaCliente.setBackground(Color.red);
        } else {
            txtCedulaCliente.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtCedulaClienteFocusLost

    private void txtCorreoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoClienteFocusGained
        if (txtCorreoCliente.getText().equals("Correo")) {
            txtCorreoCliente.setText("");
            txtCorreoCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCorreoClienteFocusGained

    private void txtCorreoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoClienteFocusLost
        if (txtCorreoCliente.getText().equals("")) {
            txtCorreoCliente.setText("Correo");
            txtCorreoCliente.setForeground(Color.gray);

        }
    }//GEN-LAST:event_txtCorreoClienteFocusLost

    private void txtContrasenaClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaClienteFocusGained
        if (String.valueOf(txtContrasenaCliente.getPassword()).equals("******")) {
            txtContrasenaCliente.setText("");
            txtContrasenaCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtContrasenaClienteFocusGained

    private void txtContrasenaClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaClienteFocusLost
        if (String.valueOf(txtContrasenaCliente.getPassword()).equals("")) {
            txtContrasenaCliente.setText("******");
            txtContrasenaCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtContrasenaClienteFocusLost

    private void checkVehiculoClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkVehiculoClienteItemStateChanged
        if (checkVehiculoCliente.getState()) {
            txtTipoDeVehiculoCliente.setEnabled(true);
            txtPlacaVehiculoCliente.setEnabled(true);
        } else {
            txtTipoDeVehiculoCliente.setEnabled(false);
            txtPlacaVehiculoCliente.setEnabled(false);
            txtTipoDeVehiculoCliente.setText("Tipo de vehiculo");
            txtTipoDeVehiculoCliente.setForeground(Color.gray);
            txtPlacaVehiculoCliente.setText("Placa del vehiculo");
            txtPlacaVehiculoCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_checkVehiculoClienteItemStateChanged

    private void txtPlacaVehiculoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoClienteFocusGained
        if (txtPlacaVehiculoCliente.getText().equals("Placa del vehiculo")) {
            txtPlacaVehiculoCliente.setText("");
            txtPlacaVehiculoCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPlacaVehiculoClienteFocusGained

    private void txtPlacaVehiculoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoClienteFocusLost
        if (txtPlacaVehiculoCliente.getText().equals("")) {
            txtPlacaVehiculoCliente.setText("Placa del vehiculo");
            txtPlacaVehiculoCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPlacaVehiculoClienteFocusLost

    private void txtTipoDeVehiculoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoDeVehiculoClienteFocusGained
        if (txtTipoDeVehiculoCliente.getText().equals("Tipo de vehiculo")) {
            txtTipoDeVehiculoCliente.setText("");
            txtTipoDeVehiculoCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTipoDeVehiculoClienteFocusGained

    private void txtTipoDeVehiculoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoDeVehiculoClienteFocusLost
        if (txtTipoDeVehiculoCliente.getText().equals("")) {
            txtTipoDeVehiculoCliente.setText("Tipo de vehiculo");
            txtTipoDeVehiculoCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTipoDeVehiculoClienteFocusLost

    private void txtNombreClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreClienteFocusLost
        if (txtNombreCliente.getText().equals("")) {
            txtNombreCliente.setText("Nombre completo");
            txtNombreCliente.setForeground(Color.gray);
        }
        if (!validarLetras(txtNombreCliente.getText()) && !txtNombreCliente.getText().equals("Nombre completo")) {
            txtNombreCliente.setBackground(Color.red);
        } else {
            txtNombreCliente.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtNombreClienteFocusLost

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        if (txtCorreoCliente.getText().equals("") || txtCorreoCliente.getText().equals("Correo")
                || String.valueOf(txtContrasenaCliente.getPassword()).equals("")
                || String.valueOf(txtContrasenaCliente.getPassword()).equals("******")
                || txtCedulaCliente.getText().equals("") || txtCedulaCliente.getText().equals("Cedula")
                || txtEdadCliente.getText().equals("") || txtEdadCliente.getText().equals("Edad")
                || txtNombreCliente.getText().equals("") || txtNombreCliente.getText().equals("Nombre completo")
                || txtTelefonoCliente.getText().equals("") || txtTelefonoCliente.getText().equals("Numero movil")) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String telefono = txtTelefonoCliente.getText();
            String nombre = txtNombreCliente.getText();
            short edad = Short.parseShort(txtEdadCliente.getText());
            String cedula = txtCedulaCliente.getText();
            String correo = txtCorreoCliente.getText();
            String contrasena = String.valueOf(txtContrasenaCliente.getPassword());
            Vehiculo vehiculo = vehiculo1();
            Cliente cliente = new Cliente(vehiculo, nombre, cedula, telefono, correo, contrasena, edad);
            if (controlador.modificarCliente(cedula, cliente)) {
                JOptionPane.showMessageDialog(this, "El cliente con cedula: " + cedula + " modificado correctamente");
                limpiarTablaCliente();
                cargarCliente();
                cleanTextFieldCliente();
            } else {
                JOptionPane.showMessageDialog(this, "El cliente con cedula: " + cedula + " no fue modificado debido a que hay un usuario con esos datos");
            }
        }
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if (txtCedulaCliente.getText().equals("") || txtCedulaCliente.getText().equals("Cedula")) {
            JOptionPane.showMessageDialog(this, "Por favor rellena el campo de cedula para eliminar el empleado");
        } else {
            String cedula = txtCedulaCliente.getText();
            if (controlador.eliminarCliente(cedula)) {
                JOptionPane.showMessageDialog(this, "El cliente con cedula: " + cedula + " fue eliminado correctamente.");
                limpiarTablaCliente();
                cargarCliente();
                cleanTextFieldCliente();
            } else {
                JOptionPane.showMessageDialog(this, "El cliente con cedula: " + cedula + " NO fue eliminado.");
            }
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void txtNombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMouseClicked
        if (txtNombreCliente.getText().equals("Nombre completo")) {
            txtNombreCliente.setText("");
            txtNombreCliente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreClienteMouseClicked

    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9]*");
    }

    public static boolean validarLetras(String datos) {
        return datos.matches("[a-zA-Z]*");
    }

    public void cargarCliente() {
        if (CentroComercial.personas.Size() != 0) {
            modeloTablaCliente = (DefaultTableModel) jTableClientes.getModel();
            Object[] ob = new Object[6];
            for (int i = 0; i < CentroComercial.personas.Size(); i++) {
                if (!(CentroComercial.personas.obtenerDato(i) instanceof Cliente)) {
                } else {
                    String vehiculo = "Si";
                    Cliente aux = (Cliente) CentroComercial.personas.obtenerDato(i);
                    ob[0] = aux.getNombre();
                    ob[1] = aux.getCorreo();
                    ob[2] = aux.getCedula();
                    ob[3] = aux.getEdad();
                    if (aux.isMulta()) {
                        ob[4] = "Si";
                    } else {
                        ob[4] = "No";
                    }
                    if (aux.getVehiculo() == null) {
                        vehiculo = "No";
                    }
                    ob[5] = vehiculo;
                    modeloTablaCliente.addRow(ob);
                }
            }
            jTableClientes.setModel(modeloTablaCliente);
        }
    }

    public void limpiarTablaCliente() {
        for (int i = 0; i < modeloTablaCliente.getRowCount(); i++) {
            modeloTablaCliente.removeRow(i);
            i = i - 1;
        }
    }

    public Vehiculo vehiculo1() {
        Vehiculo vehiculo = null;
        if (checkVehiculoCliente.getState()) {
            if (txtPlacaVehiculoCliente.getText().equals("Placa del vehiculo") || txtTipoDeVehiculoCliente.getText().equals("Tipo de vehiculo")
                    || txtPlacaVehiculoCliente.getText().equals("")
                    || txtTipoDeVehiculoCliente.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
            } else {
                String tipoVehiculo = txtTipoDeVehiculoCliente.getText();
                String placa = txtPlacaVehiculoCliente.getText();
                vehiculo = new Vehiculo(tipoVehiculo, placa);
            }
        }
        return vehiculo;
    }

    public void cleanTextFieldCliente() {
        txtTipoDeVehiculoCliente.setText("Tipo de vehiculo");
        txtTipoDeVehiculoCliente.setForeground(Color.gray);
        txtPlacaVehiculoCliente.setText("Placa del vehiculo");
        txtPlacaVehiculoCliente.setForeground(Color.gray);
        txtTelefonoCliente.setText("Numero movil");
        txtTelefonoCliente.setForeground(Color.gray);
        txtNombreCliente.setText("Nombre completo");
        txtNombreCliente.setForeground(Color.gray);
        txtEdadCliente.setText("Edad");
        txtEdadCliente.setForeground(Color.gray);
        txtCedulaCliente.setText("Cedula");
        txtCedulaCliente.setForeground(Color.gray);
        txtCorreoCliente.setText("Correo");
        txtCorreoCliente.setForeground(Color.gray);
        txtContrasenaCliente.setText("******");
        txtContrasenaCliente.setForeground(Color.gray);
        checkVehiculoCliente.setState(false);
        txtTipoDeVehiculoCliente.setEnabled(false);
        txtPlacaVehiculoCliente.setEnabled(false);
        txtTipoDeVehiculoCliente.setText("Tipo de vehiculo");
        txtTipoDeVehiculoCliente.setForeground(Color.gray);
        txtPlacaVehiculoCliente.setText("Placa del vehiculo");
        txtPlacaVehiculoCliente.setForeground(Color.gray);
    }

    public void mouseTableCliente() {
        jTableClientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtNombreCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString());
                    txtNombreCliente.setForeground(Color.black);
                    txtCorreoCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1).toString());
                    txtCorreoCliente.setForeground(Color.black);
                    txtCedulaCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 2).toString());
                    txtCedulaCliente.setForeground(Color.black);
                    Cliente cliente = (Cliente) controlador.buscarPorCedula(txtCedulaCliente.getText());
                    txtTelefonoCliente.setText(cliente.getNumeroCelular());
                    txtEdadCliente.setText(String.valueOf(cliente.getEdad()));
                    txtEdadCliente.setForeground(Color.black);
                    txtTelefonoCliente.setForeground(Color.black);
                    txtContrasenaCliente.setText(cliente.getContrasena());
                    txtContrasenaCliente.setForeground(Color.black);
                    if (cliente.getVehiculo() != null) {
                        checkVehiculoCliente.setState(true);
                        txtTipoDeVehiculoCliente.setEnabled(true);
                        txtPlacaVehiculoCliente.setEnabled(true);
                        txtTipoDeVehiculoCliente.setText(cliente.getVehiculo().getTipo());
                        txtTipoDeVehiculoCliente.setForeground(Color.black);
                        txtPlacaVehiculoCliente.setText(cliente.getVehiculo().getPlaca());
                        txtPlacaVehiculoCliente.setForeground(Color.black);
                    } else {
                        checkVehiculoCliente.setState(false);
                        txtTipoDeVehiculoCliente.setEnabled(false);
                        txtPlacaVehiculoCliente.setEnabled(false);
                        txtTipoDeVehiculoCliente.setText("Tipo de vehiculo");
                        txtTipoDeVehiculoCliente.setForeground(Color.gray);
                        txtPlacaVehiculoCliente.setText("Placa del vehiculo");
                        txtPlacaVehiculoCliente.setForeground(Color.gray);
                    }
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnRegistrarCliente;
    private java.awt.Checkbox checkVehiculoCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelConcursos;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelLocales;
    private javax.swing.JLabel jLabelRegistrar3;
    private javax.swing.JLabel jLabelSolicitudes;
    private javax.swing.JLabel jLabelVentas;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JPasswordField txtContrasenaCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtEdadCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPlacaVehiculoCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTipoDeVehiculoCliente;
    // End of variables declaration//GEN-END:variables
}
