/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorVentanaGestionarEmpleadoCentroComercial;
import excepciones.ExcepcionEmpleadoDuplicado;
import excepciones.ExcepcionNoSeEncuentraDocumento;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import src.CentroComercial;
import src.Empleado;
import src.Vehiculo;
import static ventana.VentanaGestionarCliente.validarLetras;

/**
 *
 * @author usuario
 */
public class VentanaGestionarEmpleadoCentroComercial extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaEmpleado;
    private ControladorVentanaGestionarEmpleadoCentroComercial controlador;

    /**
     * Creates new form VentanaRegistroEmpleados
     */
    public VentanaGestionarEmpleadoCentroComercial() {
        initComponents();
        setLocationRelativeTo(this);
        this.modeloTablaEmpleado = new DefaultTableModel();
        this.controlador = new ControladorVentanaGestionarEmpleadoCentroComercial();
        this.txtTipoDeVehiculoEmpleado.setEnabled(false);
        this.txtPlacaVehiculoEmpleado.setEnabled(false);
        limpiarTablaEmpleados();
        cargarTablaEmpleados();
        mouseTablEmpleado();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnRegistrarEmpleado = new javax.swing.JButton();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        txtEdadEmpleado = new javax.swing.JTextField();
        txtCedulaEmpleado = new javax.swing.JTextField();
        txtCorreoEmpleado = new javax.swing.JTextField();
        txtContrasenaEmpleado = new javax.swing.JPasswordField();
        checkVehiculoEmpleado = new java.awt.Checkbox();
        txtPlacaVehiculoEmpleado = new javax.swing.JTextField();
        txtTipoDeVehiculoEmpleado = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        jComboBoxEmpleado = new javax.swing.JComboBox<>();
        btnModificarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLocales = new javax.swing.JLabel();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelConcursos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        jLabelSolicitudes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("¿Deseas salir de la cuenta?");

        jLabelSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(51, 153, 255));
        jLabelSalir.setText("Salir");
        jLabelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Gestionar empleado"));

        btnRegistrarEmpleado.setText("Registrar");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        txtTelefonoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoEmpleado.setText("Numero movil");
        txtTelefonoEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoEmpleadoFocusLost(evt);
            }
        });

        txtEdadEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtEdadEmpleado.setText("Edad");
        txtEdadEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEdadEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadEmpleadoFocusLost(evt);
            }
        });

        txtCedulaEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtCedulaEmpleado.setText("Cedula");
        txtCedulaEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaEmpleadoFocusLost(evt);
            }
        });

        txtCorreoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoEmpleado.setText("Correo");
        txtCorreoEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoEmpleadoFocusLost(evt);
            }
        });

        txtContrasenaEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtContrasenaEmpleado.setText("******");
        txtContrasenaEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaEmpleadoFocusLost(evt);
            }
        });

        checkVehiculoEmpleado.setLabel("¿Tiene Vehiculo?");
        checkVehiculoEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkVehiculoEmpleadoItemStateChanged(evt);
            }
        });

        txtPlacaVehiculoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtPlacaVehiculoEmpleado.setText("Placa del vehiculo");
        txtPlacaVehiculoEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacaVehiculoEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaVehiculoEmpleadoFocusLost(evt);
            }
        });

        txtTipoDeVehiculoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtTipoDeVehiculoEmpleado.setText("Tipo de vehiculo");
        txtTipoDeVehiculoEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoDeVehiculoEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoDeVehiculoEmpleadoFocusLost(evt);
            }
        });

        txtNombreEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreEmpleado.setText("Nombre completo");
        txtNombreEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreEmpleadoFocusLost(evt);
            }
        });
        txtNombreEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreEmpleadoMouseClicked(evt);
            }
        });

        jComboBoxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo", "Encargado parqueadero" }));

        btnModificarEmpleado.setText("Modificar");
        btnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkVehiculoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoEmpleado)
                    .addComponent(txtEdadEmpleado)
                    .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreoEmpleado)
                    .addComponent(txtContrasenaEmpleado)
                    .addComponent(txtTipoDeVehiculoEmpleado)
                    .addComponent(txtPlacaVehiculoEmpleado)
                    .addComponent(jComboBoxEmpleado, 0, 192, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombreEmpleado))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkVehiculoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoDeVehiculoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlacaVehiculoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnRegistrarEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarEmpleado)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados registrados"));

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Cedula", "Edad", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(1).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(2).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(3).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSalir)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ADMINISTRADOR");

        jLabelLocales.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLocales.setForeground(new java.awt.Color(51, 153, 255));
        jLabelLocales.setText("Locales");
        jLabelLocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLocales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLocalesMouseClicked(evt);
            }
        });

        jLabelEmpleados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpleados.setText("Empleados");
        jLabelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelClientes.setText("Clientes");
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });

        jLabelConcursos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelConcursos.setForeground(new java.awt.Color(51, 153, 255));
        jLabelConcursos.setText("Ventas");
        jLabelConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConcursosMouseClicked(evt);
            }
        });

        jLabelVentas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(51, 153, 255));
        jLabelVentas.setText("Concursos");
        jLabelVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentasMouseClicked(evt);
            }
        });

        jLabelSolicitudes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSolicitudes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelSolicitudes.setText("Solicitudes");
        jLabelSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSolicitudesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmpleados)
                    .addComponent(jLabelLocales)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelVentas)
                    .addComponent(jLabelConcursos)
                    .addComponent(jLabelSolicitudes))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelLocales)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmpleados)
                .addGap(18, 18, 18)
                .addComponent(jLabelClientes)
                .addGap(18, 18, 18)
                .addComponent(jLabelConcursos)
                .addGap(18, 18, 18)
                .addComponent(jLabelVentas)
                .addGap(18, 18, 18)
                .addComponent(jLabelSolicitudes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        VentanaLogIn ventanaLogIn = new VentanaLogIn();
        ventanaLogIn.reinciarLogIn();
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        if (txtCorreoEmpleado.getText().equals("") || txtCorreoEmpleado.getText().equals("Correo")
                || String.valueOf(txtContrasenaEmpleado.getPassword()).equals("")
                || String.valueOf(txtContrasenaEmpleado.getPassword()).equals("******")
                || txtCedulaEmpleado.getText().equals("") || txtCedulaEmpleado.getText().equals("Cedula")
                || txtEdadEmpleado.getText().equals("") || txtEdadEmpleado.getText().equals("Edad")
                || txtNombreEmpleado.getText().equals("") || txtNombreEmpleado.getText().equals("Nombre completo")
                || txtTelefonoEmpleado.getText().equals("") || txtTelefonoEmpleado.getText().equals("Numero movil")
                || jComboBoxEmpleado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String telefono = txtTelefonoEmpleado.getText();
            String nombre = txtNombreEmpleado.getText();
            short edad = Short.parseShort(txtEdadEmpleado.getText());
            String cedula = txtCedulaEmpleado.getText();
            String correo = txtCorreoEmpleado.getText();
            String contrasena = String.valueOf(txtContrasenaEmpleado.getPassword());
            Vehiculo vehiculo = vehiculo();
            String rol = String.valueOf(jComboBoxEmpleado.getSelectedItem());
            Empleado empleado = new Empleado(vehiculo, rol, nombre, cedula, telefono, correo, contrasena, edad);
            try {
                if (controlador.anadirEmpleadoCentroComercial(empleado)) {
                    JOptionPane.showMessageDialog(this, "Registrado correctamente");
                    limpiarTablaEmpleados();
                    cargarTablaEmpleados();
                    cleanTextFieldEmpleado();
                }
            } catch (ExcepcionEmpleadoDuplicado ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void txtTelefonoEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoEmpleadoFocusGained
        if (txtTelefonoEmpleado.getText().equals("Numero movil")) {
            txtTelefonoEmpleado.setText("");
            txtTelefonoEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTelefonoEmpleadoFocusGained

    private void txtTelefonoEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoEmpleadoFocusLost
        if (txtTelefonoEmpleado.getText().equals("")) {
            txtTelefonoEmpleado.setText("Numero movil");
            txtTelefonoEmpleado.setForeground(Color.gray);
        }
        if (!validarNumeros(txtTelefonoEmpleado.getText()) && !txtTelefonoEmpleado.getText().equals("Numero movil")) {
            txtTelefonoEmpleado.setBackground(Color.red);
        } else {
            txtTelefonoEmpleado.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtTelefonoEmpleadoFocusLost

    private void txtEdadEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadEmpleadoFocusGained
        if (txtEdadEmpleado.getText().equals("Edad")) {
            txtEdadEmpleado.setText("");
            txtEdadEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEdadEmpleadoFocusGained

    private void txtEdadEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadEmpleadoFocusLost
        if (txtEdadEmpleado.getText().equals("")) {
            txtEdadEmpleado.setText("Edad");
            txtEdadEmpleado.setForeground(Color.gray);
        }
        if (!validarNumeros(txtEdadEmpleado.getText()) && !txtEdadEmpleado.getText().equals("Edad")) {
            txtEdadEmpleado.setBackground(Color.red);
        } else {
            txtEdadEmpleado.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtEdadEmpleadoFocusLost

    private void txtCedulaEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaEmpleadoFocusGained
        if (txtCedulaEmpleado.getText().equals("Cedula")) {
            txtCedulaEmpleado.setText("");
            txtCedulaEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCedulaEmpleadoFocusGained

    private void txtCedulaEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaEmpleadoFocusLost
        if (txtCedulaEmpleado.getText().equals("")) {
            txtCedulaEmpleado.setText("Cedula");
            txtCedulaEmpleado.setForeground(Color.gray);
        }
        if (!validarNumeros(txtCedulaEmpleado.getText()) && !txtCedulaEmpleado.getText().equals("Cedula")) {
            txtCedulaEmpleado.setBackground(Color.red);
        } else {
            txtCedulaEmpleado.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtCedulaEmpleadoFocusLost

    private void txtCorreoEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoEmpleadoFocusGained
        if (txtCorreoEmpleado.getText().equals("Correo")) {
            txtCorreoEmpleado.setText("");
            txtCorreoEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCorreoEmpleadoFocusGained

    private void txtCorreoEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoEmpleadoFocusLost
        if (txtCorreoEmpleado.getText().equals("")) {
            txtCorreoEmpleado.setText("Correo");
            txtCorreoEmpleado.setForeground(Color.gray);

        }
    }//GEN-LAST:event_txtCorreoEmpleadoFocusLost

    private void txtContrasenaEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaEmpleadoFocusGained
        if (String.valueOf(txtContrasenaEmpleado.getPassword()).equals("******")) {
            txtContrasenaEmpleado.setText("");
            txtContrasenaEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtContrasenaEmpleadoFocusGained

    private void txtContrasenaEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaEmpleadoFocusLost
        if (String.valueOf(txtContrasenaEmpleado.getPassword()).equals("")) {
            txtContrasenaEmpleado.setText("******");
            txtContrasenaEmpleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtContrasenaEmpleadoFocusLost

    private void checkVehiculoEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkVehiculoEmpleadoItemStateChanged
        if (checkVehiculoEmpleado.getState()) {
            txtTipoDeVehiculoEmpleado.setEnabled(true);
            txtPlacaVehiculoEmpleado.setEnabled(true);
        } else {
            txtTipoDeVehiculoEmpleado.setEnabled(false);
            txtPlacaVehiculoEmpleado.setEnabled(false);
            txtTipoDeVehiculoEmpleado.setText("Tipo de vehiculo");
            txtTipoDeVehiculoEmpleado.setForeground(Color.gray);
            txtPlacaVehiculoEmpleado.setText("Placa del vehiculo");
            txtPlacaVehiculoEmpleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_checkVehiculoEmpleadoItemStateChanged

    private void txtPlacaVehiculoEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoEmpleadoFocusGained
        if (txtPlacaVehiculoEmpleado.getText().equals("Placa del vehiculo")) {
            txtPlacaVehiculoEmpleado.setText("");
            txtPlacaVehiculoEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPlacaVehiculoEmpleadoFocusGained

    private void txtPlacaVehiculoEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoEmpleadoFocusLost
        if (txtPlacaVehiculoEmpleado.getText().equals("")) {
            txtPlacaVehiculoEmpleado.setText("Placa del vehiculo");
            txtPlacaVehiculoEmpleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPlacaVehiculoEmpleadoFocusLost

    private void txtTipoDeVehiculoEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoDeVehiculoEmpleadoFocusGained
        if (txtTipoDeVehiculoEmpleado.getText().equals("Tipo de vehiculo")) {
            txtTipoDeVehiculoEmpleado.setText("");
            txtTipoDeVehiculoEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTipoDeVehiculoEmpleadoFocusGained

    private void txtTipoDeVehiculoEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoDeVehiculoEmpleadoFocusLost
        if (txtTipoDeVehiculoEmpleado.getText().equals("")) {
            txtTipoDeVehiculoEmpleado.setText("Tipo de vehiculo");
            txtTipoDeVehiculoEmpleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTipoDeVehiculoEmpleadoFocusLost

    private void txtNombreEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoFocusLost
        if (txtNombreEmpleado.getText().equals("")) {
            txtNombreEmpleado.setText("Nombre completo");
            txtNombreEmpleado.setForeground(Color.gray);
        }
        if (!validarLetras(txtNombreEmpleado.getText()) && !txtNombreEmpleado.getText().equals("Nombre completo")) {
            txtNombreEmpleado.setBackground(Color.red);
        } else {
            txtNombreEmpleado.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtNombreEmpleadoFocusLost

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed
        if (txtCorreoEmpleado.getText().equals("") || txtCorreoEmpleado.getText().equals("Correo")
                || String.valueOf(txtContrasenaEmpleado.getPassword()).equals("")
                || String.valueOf(txtContrasenaEmpleado.getPassword()).equals("******")
                || txtCedulaEmpleado.getText().equals("") || txtCedulaEmpleado.getText().equals("Cedula")
                || txtEdadEmpleado.getText().equals("") || txtEdadEmpleado.getText().equals("Edad")
                || txtNombreEmpleado.getText().equals("") || txtNombreEmpleado.getText().equals("Nombre completo")
                || txtTelefonoEmpleado.getText().equals("") || txtTelefonoEmpleado.getText().equals("Numero movil")
                || jComboBoxEmpleado.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String rol = String.valueOf(jComboBoxEmpleado.getSelectedItem());
            String telefono = txtTelefonoEmpleado.getText();
            String nombre = txtNombreEmpleado.getText();
            short edad = Short.parseShort(txtEdadEmpleado.getText());
            String cedula = txtCedulaEmpleado.getText();
            String correo = txtCorreoEmpleado.getText();
            String contrasena = String.valueOf(txtContrasenaEmpleado.getPassword());
            Vehiculo vehiculo = vehiculo();
            Empleado empleado = new Empleado(vehiculo, rol, nombre, cedula, telefono, correo, contrasena, edad);
            try {
                if (controlador.modificarEmpleadoCentroComercial(cedula, empleado)) {
                    JOptionPane.showMessageDialog(this, "El empleado con cedula: " + cedula + " modificado correctamente");
                    limpiarTablaEmpleados();
                    cargarTablaEmpleados();
                    cleanTextFieldEmpleado();
                } else {
                    JOptionPane.showMessageDialog(this, "El empleado con cedula: " + cedula + " no fue modificado debido a que hay un usuario con esos datos");
                }
            } catch (ExcepcionNoSeEncuentraDocumento ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        if (txtCedulaEmpleado.getText().equals("") || txtCedulaEmpleado.getText().equals("Cedula")) {
            JOptionPane.showMessageDialog(this, "Por favor rellena el campo de cedula para eliminar el empleado");
        } else {
            String cedula = txtCedulaEmpleado.getText();
            if (controlador.eliminarEmpleadoCentroComercial(cedula)) {
                JOptionPane.showMessageDialog(this, "El empleado con cedula: " + cedula + " fue eliminado correctamente.");
                limpiarTablaEmpleados();
                cargarTablaEmpleados();
                cleanTextFieldEmpleado();
            } else {
                JOptionPane.showMessageDialog(this, "El empleado con cedula: " + cedula + " NO fue eliminado.");
            }
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void jLabelLocalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLocalesMouseClicked
        VentanaAdministrador ventanaAdministrador = new VentanaAdministrador();
        ventanaAdministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelLocalesMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        VentanaGestionarCliente ventanaGestionarCliente = new VentanaGestionarCliente();
        ventanaGestionarCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConcursosMouseClicked
        VentanaVentasGeneradas ventanaVentasGeneradas = new VentanaVentasGeneradas();
        ventanaVentasGeneradas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelConcursosMouseClicked

    private void jLabelVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentasMouseClicked
        VentanaGestionarConcurso ventanaGestionarConcurso = new VentanaGestionarConcurso();
        ventanaGestionarConcurso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelVentasMouseClicked

    private void jLabelSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSolicitudesMouseClicked
        VentanaGestionarSolicitudes ventanaGestionarSolicitudes = new VentanaGestionarSolicitudes();
        ventanaGestionarSolicitudes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSolicitudesMouseClicked

    private void txtNombreEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoMouseClicked
        if (txtNombreEmpleado.getText().equals("Nombre completo")) {
            txtNombreEmpleado.setText("");
            txtNombreEmpleado.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreEmpleadoMouseClicked
    public void cargarTablaEmpleados() {
        if (CentroComercial.personas.Size() != 0) {
            modeloTablaEmpleado = (DefaultTableModel) jTableEmpleados.getModel();
            Object[] ob = new Object[5];
            for (int i = 0; i < CentroComercial.personas.Size(); i++) {
                if (!(CentroComercial.personas.obtenerDato(i) instanceof Empleado)) {
                } else {
                    Empleado aux = (Empleado) CentroComercial.personas.obtenerDato(i);
                    ob[0] = aux.getNombre();
                    ob[1] = aux.getCorreo();
                    ob[2] = aux.getCedula();
                    ob[3] = aux.getEdad();
                    ob[4] = aux.getRol();
                    modeloTablaEmpleado.addRow(ob);
                }
            }
            jTableEmpleados.setModel(modeloTablaEmpleado);
        }
    }

    public void limpiarTablaEmpleados() {
        for (int i = 0; i < modeloTablaEmpleado.getRowCount(); i++) {
            modeloTablaEmpleado.removeRow(i);
            i = i - 1;
        }
    }

    public Vehiculo vehiculo() {
        Vehiculo vehiculo = null;
        if (checkVehiculoEmpleado.getState()) {
            if (txtPlacaVehiculoEmpleado.getText().equals("Placa del vehiculo") || txtTipoDeVehiculoEmpleado.getText().equals("Tipo de vehiculo")
                    || txtPlacaVehiculoEmpleado.getText().equals("")
                    || txtTipoDeVehiculoEmpleado.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
            } else {
                String tipoVehiculo = txtTipoDeVehiculoEmpleado.getText();
                String placa = txtPlacaVehiculoEmpleado.getText();
                vehiculo = new Vehiculo(tipoVehiculo, placa);
            }
        }
        return vehiculo;
    }

    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9]*");
    }

    public static boolean validarLetras(String datos) {
        return datos.matches("[a-zA-Z]*");
    }

    public void cleanTextFieldEmpleado() {
        txtPlacaVehiculoEmpleado.setText("Placa del vehiculo");
        txtPlacaVehiculoEmpleado.setForeground(Color.gray);
        txtTipoDeVehiculoEmpleado.setText("Tipo de vehiculo");
        txtTipoDeVehiculoEmpleado.setForeground(Color.gray);
        txtTelefonoEmpleado.setText("Numero movil");
        txtTelefonoEmpleado.setForeground(Color.gray);
        txtNombreEmpleado.setText("Nombre completo");
        txtNombreEmpleado.setForeground(Color.gray);
        txtEdadEmpleado.setText("Edad");
        txtEdadEmpleado.setForeground(Color.gray);
        txtCedulaEmpleado.setText("Cedula");
        txtCedulaEmpleado.setForeground(Color.gray);
        txtCorreoEmpleado.setText("Correo");
        txtCorreoEmpleado.setForeground(Color.gray);
        txtContrasenaEmpleado.setText("******");
        txtContrasenaEmpleado.setForeground(Color.gray);
        jComboBoxEmpleado.setSelectedIndex(0);
        checkVehiculoEmpleado.setState(false);
        txtTipoDeVehiculoEmpleado.setEnabled(false);
        txtPlacaVehiculoEmpleado.setEnabled(false);
    }

    public void mouseTablEmpleado() {
        jTableEmpleados.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtNombreEmpleado.setText(jTableEmpleados.getValueAt(jTableEmpleados.getSelectedRow(), 0).toString());
                    txtNombreEmpleado.setForeground(Color.black);
                    txtCorreoEmpleado.setText(jTableEmpleados.getValueAt(jTableEmpleados.getSelectedRow(), 1).toString());
                    txtCorreoEmpleado.setForeground(Color.black);
                    txtCedulaEmpleado.setText(jTableEmpleados.getValueAt(jTableEmpleados.getSelectedRow(), 2).toString());
                    txtCedulaEmpleado.setForeground(Color.black);
                    jComboBoxEmpleado.setSelectedItem(jTableEmpleados.getValueAt(jTableEmpleados.getSelectedRow(), 3).toString());
                    Empleado empleado = (Empleado) controlador.buscarPorCedula(txtCedulaEmpleado.getText());
                    txtTelefonoEmpleado.setText(empleado.getNumeroCelular());
                    txtEdadEmpleado.setText(String.valueOf(empleado.getEdad()));
                    txtEdadEmpleado.setForeground(Color.black);
                    txtTelefonoEmpleado.setForeground(Color.black);
                    txtContrasenaEmpleado.setText(empleado.getContrasena());
                    txtContrasenaEmpleado.setForeground(Color.black);
                    if (empleado.getVehiculo() != null) {
                        checkVehiculoEmpleado.setState(true);
                        txtTipoDeVehiculoEmpleado.setEnabled(true);
                        txtPlacaVehiculoEmpleado.setEnabled(true);
                        txtTipoDeVehiculoEmpleado.setText(empleado.getVehiculo().getTipo());
                        txtTipoDeVehiculoEmpleado.setForeground(Color.black);
                        txtPlacaVehiculoEmpleado.setText(empleado.getVehiculo().getPlaca());
                        txtPlacaVehiculoEmpleado.setForeground(Color.black);
                    } else {
                        checkVehiculoEmpleado.setState(false);
                        txtTipoDeVehiculoEmpleado.setEnabled(false);
                        txtPlacaVehiculoEmpleado.setEnabled(false);
                        txtTipoDeVehiculoEmpleado.setText("Tipo de vehiculo");
                        txtTipoDeVehiculoEmpleado.setForeground(Color.gray);
                        txtPlacaVehiculoEmpleado.setText("Placa del vehiculo");
                        txtPlacaVehiculoEmpleado.setForeground(Color.gray);
                    }
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarEmpleadoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarEmpleadoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarEmpleadoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarEmpleadoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionarEmpleadoCentroComercial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnRegistrarEmpleado;
    private java.awt.Checkbox checkVehiculoEmpleado;
    private javax.swing.JComboBox<String> jComboBoxEmpleado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelConcursos;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelLocales;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelSolicitudes;
    private javax.swing.JLabel jLabelVentas;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField txtCedulaEmpleado;
    private javax.swing.JPasswordField txtContrasenaEmpleado;
    private javax.swing.JTextField txtCorreoEmpleado;
    private javax.swing.JTextField txtEdadEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtPlacaVehiculoEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    private javax.swing.JTextField txtTipoDeVehiculoEmpleado;
    // End of variables declaration//GEN-END:variables
}
