/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorVentanaGestionarConcurso;
import excepciones.ExcepcionConcursoDuplicado;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import src.CentroComercial;
import src.Cliente;
import src.Concurso;

/**
 *
 * @author usuario
 */
public class VentanaGestionarConcurso extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaHistorialConcurso;
    private DefaultTableModel modeloTablaConcurso;
    private ControladorVentanaGestionarConcurso controlador;

    /**
     * Creates new form VentanaConcursos
     */
    public VentanaGestionarConcurso() {
        initComponents();
        setLocationRelativeTo(this);
        this.modeloTablaHistorialConcurso = new DefaultTableModel();
        this.modeloTablaConcurso = new DefaultTableModel();
        this.controlador = new ControladorVentanaGestionarConcurso();
        this.txtCorreoDeGanador.setEnabled(false);
        limpiarTablaConcurso();
        limpiarTablaConcursoHistorial();
        cargarTablaConcurso();
        cargarTablaConcursoHistorial();
        mouseTableConcurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelRegistrar5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableConcurso = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        btnRegistrarConcurso = new javax.swing.JButton();
        txtPremioConcurso = new javax.swing.JTextField();
        txtValorMinimoConcurso = new javax.swing.JTextField();
        checkConcurso = new java.awt.Checkbox();
        txtNombreConcurso = new javax.swing.JTextField();
        btnModificarConcurso = new javax.swing.JButton();
        btnEliminarConcurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoConcurso = new javax.swing.JTextField();
        btnRegistrarConcurso1 = new javax.swing.JButton();
        jDateChooserConcursoIni = new com.toedter.calendar.JDateChooser();
        jDateChooserConcursoFin = new com.toedter.calendar.JDateChooser();
        txtCorreoDeGanador = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableConcursoHistorial = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLocales = new javax.swing.JLabel();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelConcursos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        jLabelSolicitudes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("¿Deseas salir de la cuenta?");

        jLabelRegistrar5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelRegistrar5.setForeground(new java.awt.Color(51, 153, 255));
        jLabelRegistrar5.setText("Salir");
        jLabelRegistrar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrar5MouseClicked(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Concursos vigentes"));

        jTableConcurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Premio", "valor minimo", "Fecha inicio", "Fecha fin", "Participantes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableConcurso);
        if (jTableConcurso.getColumnModel().getColumnCount() > 0) {
            jTableConcurso.getColumnModel().getColumn(0).setResizable(false);
            jTableConcurso.getColumnModel().getColumn(1).setResizable(false);
            jTableConcurso.getColumnModel().getColumn(2).setResizable(false);
            jTableConcurso.getColumnModel().getColumn(3).setResizable(false);
            jTableConcurso.getColumnModel().getColumn(4).setResizable(false);
            jTableConcurso.getColumnModel().getColumn(5).setResizable(false);
            jTableConcurso.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Gestionar concurso"));

        btnRegistrarConcurso.setText("Registrar");
        btnRegistrarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConcursoActionPerformed(evt);
            }
        });

        txtPremioConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtPremioConcurso.setText("Premio concurso");
        txtPremioConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPremioConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPremioConcursoFocusLost(evt);
            }
        });

        txtValorMinimoConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtValorMinimoConcurso.setText("Valor minimo para participar");
        txtValorMinimoConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorMinimoConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorMinimoConcursoFocusLost(evt);
            }
        });

        checkConcurso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkConcurso.setLabel("¿Marcar ganador?");
        checkConcurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkConcursoItemStateChanged(evt);
            }
        });

        txtNombreConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreConcurso.setText("Nombre concurso");
        txtNombreConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreConcursoFocusLost(evt);
            }
        });

        btnModificarConcurso.setText("Modificar");
        btnModificarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarConcursoActionPerformed(evt);
            }
        });

        btnEliminarConcurso.setText("Eliminar");
        btnEliminarConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConcursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha inicio:");

        jLabel9.setText("Fecha de finalizacion:");

        txtCodigoConcurso.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoConcurso.setText("Codigo concurso");
        txtCodigoConcurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoConcursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoConcursoFocusLost(evt);
            }
        });

        btnRegistrarConcurso1.setText("Limpiar datos");
        btnRegistrarConcurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarConcurso1ActionPerformed(evt);
            }
        });

        txtCorreoDeGanador.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoDeGanador.setText("Correo de ganador");
        txtCorreoDeGanador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoDeGanadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoDeGanadorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCodigoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtNombreConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtPremioConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtValorMinimoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addComponent(jLabel9)
            .addComponent(checkConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(btnRegistrarConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnModificarConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(btnRegistrarConcurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnEliminarConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jDateChooserConcursoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jDateChooserConcursoFin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtCorreoDeGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtCodigoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtNombreConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtPremioConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtValorMinimoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserConcursoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserConcursoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(checkConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCorreoDeGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarConcurso)
                    .addComponent(btnModificarConcurso))
                .addGap(7, 7, 7)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarConcurso1)
                    .addComponent(btnEliminarConcurso))
                .addGap(21, 21, 21))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial de concursos"));

        jTableConcursoHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Premio", "valor minimo", "Fecha inicio", "Fecha fin", "Ganador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableConcursoHistorial);
        if (jTableConcursoHistorial.getColumnModel().getColumnCount() > 0) {
            jTableConcursoHistorial.getColumnModel().getColumn(0).setResizable(false);
            jTableConcursoHistorial.getColumnModel().getColumn(1).setResizable(false);
            jTableConcursoHistorial.getColumnModel().getColumn(2).setResizable(false);
            jTableConcursoHistorial.getColumnModel().getColumn(3).setResizable(false);
            jTableConcursoHistorial.getColumnModel().getColumn(4).setResizable(false);
            jTableConcursoHistorial.getColumnModel().getColumn(5).setResizable(false);
            jTableConcursoHistorial.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRegistrar5)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelRegistrar5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ADMINISTRADOR");

        jLabelLocales.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLocales.setForeground(new java.awt.Color(51, 153, 255));
        jLabelLocales.setText("Locales");
        jLabelLocales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLocales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLocalesMouseClicked(evt);
            }
        });

        jLabelEmpleados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelEmpleados.setForeground(new java.awt.Color(51, 153, 255));
        jLabelEmpleados.setText("Empleados");
        jLabelEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmpleadosMouseClicked(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelClientes.setText("Clientes");
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });

        jLabelConcursos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelConcursos.setForeground(new java.awt.Color(51, 153, 255));
        jLabelConcursos.setText("Ventas");
        jLabelConcursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConcursosMouseClicked(evt);
            }
        });

        jLabelVentas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVentas.setText("Concursos");
        jLabelVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelSolicitudes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSolicitudes.setForeground(new java.awt.Color(51, 153, 255));
        jLabelSolicitudes.setText("Solicitudes");
        jLabelSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSolicitudesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmpleados)
                    .addComponent(jLabelLocales)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelVentas)
                    .addComponent(jLabelConcursos)
                    .addComponent(jLabelSolicitudes))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelLocales)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmpleados)
                .addGap(18, 18, 18)
                .addComponent(jLabelClientes)
                .addGap(18, 18, 18)
                .addComponent(jLabelConcursos)
                .addGap(18, 18, 18)
                .addComponent(jLabelVentas)
                .addGap(18, 18, 18)
                .addComponent(jLabelSolicitudes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegistrar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrar5MouseClicked
        VentanaLogIn ventanaLogIn = new VentanaLogIn();
        ventanaLogIn.reinciarLogIn();
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegistrar5MouseClicked

    private void btnRegistrarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConcursoActionPerformed
        if (txtNombreConcurso.getText().isEmpty()
                || txtNombreConcurso.getText().equals("Nombre concurso")
                || txtPremioConcurso.getText().equals("Premio concurso")
                || txtPremioConcurso.getText().isEmpty()
                || txtValorMinimoConcurso.getText().equals("Valor minimo para participar")
                || txtValorMinimoConcurso.getText().isEmpty()
                || jDateChooserConcursoFin.getDate() == null
                || jDateChooserConcursoIni.getDate() == null
                || txtCodigoConcurso.getText().isEmpty() || txtCodigoConcurso.getText().equals("Codigo concurso")) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            int codigo = Integer.parseInt(txtCodigoConcurso.getText());
            String nombre = txtNombreConcurso.getText();
            String premio = txtPremioConcurso.getText();
            float valorMinimo = Float.parseFloat(txtValorMinimoConcurso.getText());
            Date fechaInicio = jDateChooserConcursoIni.getDate();
            Date fechaFin = jDateChooserConcursoFin.getDate();
            boolean check = true;
            Concurso concurso = new Concurso(valorMinimo, check, nombre, premio, fechaInicio, fechaFin);
            try {
                concurso.setCodigo(codigo);
                if (controlador.anadirConcurso(concurso)) {
                    JOptionPane.showMessageDialog(this, "Concurso llamado: " + concurso.getNombreConcurso() + " fue registrado correctamente");
                    limpiarTablaConcurso();
                    limpiarTablaConcursoHistorial();
                    cargarTablaConcurso();
                    cargarTablaConcursoHistorial();
                    cleanTextFieldConcurso();
                }
            } catch (ExcepcionConcursoDuplicado ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarConcursoActionPerformed

    private void txtPremioConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPremioConcursoFocusGained
        if (txtPremioConcurso.getText().equals("Premio concurso")) {
            txtPremioConcurso.setText("");
            txtPremioConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPremioConcursoFocusGained

    private void txtPremioConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPremioConcursoFocusLost
        if (txtPremioConcurso.getText().equals("")) {
            txtPremioConcurso.setText("Premio concurso");
            txtPremioConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPremioConcursoFocusLost

    private void txtValorMinimoConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorMinimoConcursoFocusGained
        if (txtValorMinimoConcurso.getText().equals("Valor minimo para participar")) {
            txtValorMinimoConcurso.setText("");
            txtValorMinimoConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtValorMinimoConcursoFocusGained

    private void txtValorMinimoConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorMinimoConcursoFocusLost
        if (txtValorMinimoConcurso.getText().equals("")) {
            txtValorMinimoConcurso.setText("Valor minimo para participar");
            txtValorMinimoConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtValorMinimoConcursoFocusLost

    private void txtNombreConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreConcursoFocusGained
        if (txtNombreConcurso.getText().equals("Nombre concurso")) {
            txtNombreConcurso.setText("");
            txtNombreConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreConcursoFocusGained

    private void txtNombreConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreConcursoFocusLost
        if (txtNombreConcurso.getText().equals("")) {
            txtNombreConcurso.setText("Nombre concurso");
            txtNombreConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreConcursoFocusLost

    private void btnModificarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarConcursoActionPerformed
        if (txtNombreConcurso.getText().equals("")
                || txtNombreConcurso.getText().equals("Nombre concurso")
                || txtPremioConcurso.getText().equals("Premio concurso")
                || txtPremioConcurso.getText().equals("")
                || txtValorMinimoConcurso.getText().equals("Valor minimo para participar")
                || txtValorMinimoConcurso.getText().equals("")
                || jDateChooserConcursoFin.getDate() == null
                || jDateChooserConcursoIni.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            txtCorreoDeGanador.getText();
            String nombre = txtNombreConcurso.getText();
            String premio = txtPremioConcurso.getText();
            float valorMinimo = Float.parseFloat(txtValorMinimoConcurso.getText());
            Date fechaInicio = jDateChooserConcursoIni.getDate();
            Date fechaFin = jDateChooserConcursoFin.getDate();
            boolean check = false;
            Concurso concurso = new Concurso(valorMinimo, check, nombre, premio, fechaInicio, fechaFin);
            if (checkConcurso.getState()) {
                String correo = txtCodigoConcurso.getText();
                Cliente cliente = controlador.buscarClientePorUsuario(correo);
                concurso.setGanador(cliente);
            }
            if (controlador.modificarConcurso(concurso.getCodigo(), concurso)) {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + concurso.getCodigo() + " modificado correctamente.");
                limpiarTablaConcurso();
                cargarTablaConcurso();
                cleanTextFieldConcurso();
            } else {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + concurso.getCodigo() + " no fue modificado.");
            }
        }
    }//GEN-LAST:event_btnModificarConcursoActionPerformed

    private void btnEliminarConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConcursoActionPerformed
        if (txtCodigoConcurso.getText().equals("") || txtCodigoConcurso.getText().equals("Codigo concurso")) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona el concurso que deseas eliminar.");
        } else {
            int codigo = Integer.parseInt(txtCodigoConcurso.getText());
            if (controlador.eliminarConcurso(codigo)) {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + codigo + " fue eliminado correctamente.");
                limpiarTablaConcurso();
                cargarTablaConcurso();
                cleanTextFieldConcurso();
            } else {
                JOptionPane.showMessageDialog(this, "El concurso con codigo: " + codigo + " NO fue eliminado.");
            }
        }
    }//GEN-LAST:event_btnEliminarConcursoActionPerformed

    private void btnRegistrarConcurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConcurso1ActionPerformed
        cleanTextFieldConcurso();
    }//GEN-LAST:event_btnRegistrarConcurso1ActionPerformed

    private void jLabelLocalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLocalesMouseClicked
        VentanaAdministrador ventanaAdministrador = new VentanaAdministrador();
        ventanaAdministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelLocalesMouseClicked

    private void jLabelEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmpleadosMouseClicked
        VentanaGestionarEmpleadoCentroComercial ventanaRegistroEmpleados = new VentanaGestionarEmpleadoCentroComercial();
        ventanaRegistroEmpleados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEmpleadosMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        VentanaGestionarCliente ventanaGestionarCliente = new VentanaGestionarCliente();
        ventanaGestionarCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelConcursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConcursosMouseClicked
        VentanaVentasGeneradas ventanaVentasGeneradas = new VentanaVentasGeneradas();
        ventanaVentasGeneradas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelConcursosMouseClicked

    private void jLabelSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSolicitudesMouseClicked
        VentanaGestionarSolicitudes ventanaGestionarSolicitudes = new VentanaGestionarSolicitudes();
        ventanaGestionarSolicitudes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSolicitudesMouseClicked

    private void txtCodigoConcursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoConcursoFocusGained
        if (txtCodigoConcurso.getText().equals("Codigo concurso")) {
            txtCodigoConcurso.setText("");
            txtCodigoConcurso.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCodigoConcursoFocusGained

    private void txtCodigoConcursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoConcursoFocusLost
        if (txtCodigoConcurso.getText().equals("")) {
            txtCodigoConcurso.setText("Codigo concurso");
            txtCodigoConcurso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCodigoConcursoFocusLost

    private void txtCorreoDeGanadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoDeGanadorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoDeGanadorFocusGained

    private void txtCorreoDeGanadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoDeGanadorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoDeGanadorFocusLost

    private void checkConcursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkConcursoItemStateChanged
        if (checkConcurso.getState()) {
            txtCorreoDeGanador.setEnabled(true);
        } else {
            txtCorreoDeGanador.setEnabled(false);
        }
    }//GEN-LAST:event_checkConcursoItemStateChanged
    public void cargarTablaConcurso() {
        modeloTablaConcurso = (DefaultTableModel) jTableConcurso.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < CentroComercial.concursos.Size(); i++) {
            if (CentroComercial.concursos.obtenerDato(i).isEstado()) {
                ob[0] = CentroComercial.concursos.obtenerDato(i).getCodigo();
                ob[1] = CentroComercial.concursos.obtenerDato(i).getNombreConcurso();
                ob[2] = CentroComercial.concursos.obtenerDato(i).getPremioConcurso();
                ob[3] = CentroComercial.concursos.obtenerDato(i).getValorMinimo();
                ob[4] = CentroComercial.concursos.obtenerDato(i).getFechaIncioConcurso();
                ob[5] = CentroComercial.concursos.obtenerDato(i).getFechaFinConcurso();
                ob[6] = CentroComercial.concursos.obtenerDato(i).getParticipantes().Size();
                modeloTablaConcurso.addRow(ob);
            }
        }
        jTableConcurso.setModel(modeloTablaConcurso);
    }

    public void limpiarTablaConcurso() {
        for (int i = 0; i < modeloTablaConcurso.getRowCount(); i++) {
            modeloTablaConcurso.removeRow(i);
            i = i - 1;
        }
    }

    public void cargarTablaConcursoHistorial() {
        modeloTablaHistorialConcurso = (DefaultTableModel) jTableConcursoHistorial.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < CentroComercial.historialConcursos.getConcursos().Size(); i++) {
            if (CentroComercial.historialConcursos.getConcursos().obtenerDato(i).isEstado()) {
                ob[0] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getCodigo();
                ob[1] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getNombreConcurso();
                ob[2] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getPremioConcurso();
                ob[3] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getValorMinimo();
                ob[4] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getFechaIncioConcurso();
                ob[5] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getFechaFinConcurso();
                if (CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getGanador() == null) {
                    ob[6] = "";
                } else {
                    ob[6] = CentroComercial.historialConcursos.getConcursos().obtenerDato(i).getGanador().getNombre();
                }
                modeloTablaHistorialConcurso.addRow(ob);
            }
        }
        jTableConcursoHistorial.setModel(modeloTablaHistorialConcurso);
    }

    public void limpiarTablaConcursoHistorial() {
        for (int i = 0; i < modeloTablaHistorialConcurso.getRowCount(); i++) {
            modeloTablaHistorialConcurso.removeRow(i);
            i = i - 1;
        }
    }

    public void cleanTextFieldConcurso() {
        txtCodigoConcurso.setText("Codigo concurso");
        txtCodigoConcurso.setForeground(Color.gray);
        txtNombreConcurso.setText("Nombre concurso");
        txtNombreConcurso.setForeground(Color.gray);
        txtValorMinimoConcurso.setText("Valor minimo para participar");
        txtValorMinimoConcurso.setForeground(Color.gray);
        txtPremioConcurso.setText("Premio concurso");
        txtPremioConcurso.setForeground(Color.gray);
        jDateChooserConcursoIni.setDate(null);
        jDateChooserConcursoFin.setDate(null);
        checkConcurso.setState(false);
    }

    public void mouseTableConcurso() {
        jTableConcurso.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtCodigoConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 0).toString());
                    txtCodigoConcurso.setForeground(Color.black);
                    txtNombreConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 1).toString());
                    txtNombreConcurso.setForeground(Color.black);
                    txtPremioConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 2).toString());
                    txtPremioConcurso.setForeground(Color.black);
                    txtValorMinimoConcurso.setText(jTableConcurso.getValueAt(jTableConcurso.getSelectedRow(), 3).toString());
                    txtValorMinimoConcurso.setForeground(Color.black);
                    Concurso concurso = controlador.buscarPorConcurso(Integer.parseInt(txtCodigoConcurso.getText()));
                    jDateChooserConcursoIni.setDate(concurso.getFechaIncioConcurso());
                    jDateChooserConcursoFin.setDate(concurso.getFechaFinConcurso());
                    checkConcurso.setState(concurso.isEstado());
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionarConcurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarConcurso;
    private javax.swing.JButton btnModificarConcurso;
    private javax.swing.JButton btnRegistrarConcurso;
    private javax.swing.JButton btnRegistrarConcurso1;
    private java.awt.Checkbox checkConcurso;
    private com.toedter.calendar.JDateChooser jDateChooserConcursoFin;
    private com.toedter.calendar.JDateChooser jDateChooserConcursoIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelConcursos;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelLocales;
    private javax.swing.JLabel jLabelRegistrar5;
    private javax.swing.JLabel jLabelSolicitudes;
    private javax.swing.JLabel jLabelVentas;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableConcurso;
    private javax.swing.JTable jTableConcursoHistorial;
    private javax.swing.JTextField txtCodigoConcurso;
    private javax.swing.JTextField txtCorreoDeGanador;
    private javax.swing.JTextField txtNombreConcurso;
    private javax.swing.JTextField txtPremioConcurso;
    private javax.swing.JTextField txtValorMinimoConcurso;
    // End of variables declaration//GEN-END:variables
}
