/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import controlador.ControladorVentanaEncargadoInventario;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import src.Articulo;
import src.CentroComercial;
import src.Negocio;

/**
 *
 * @author Acer
 */
public class VentanaEncargadoInventario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    private ControladorVentanaEncargadoInventario controlador;
    private DefaultTableModel modelo;
    private Negocio negocio;

    public VentanaEncargadoInventario(Negocio negocio) {
        initComponents();
        setLocationRelativeTo(this);
        this.controlador = new ControladorVentanaEncargadoInventario(negocio);
        this.negocio = negocio;
        this.modelo = new DefaultTableModel();
        this.txtDescuento.setEnabled(false);
        limpiarTabla();
        cargar();
        mouseTablArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtDescripcion = new javax.swing.JTextArea();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        txtDescuento = new javax.swing.JTextField();
        checkDescuento = new java.awt.Checkbox();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtCodigoArticulo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabelRegistrar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ENCARGADO");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("BIENVENIDO");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("DE INVENTARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Agregar articulo a inventario"));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidad.setText("Cantidad");
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });

        txtValor.setForeground(new java.awt.Color(153, 153, 153));
        txtValor.setText("Valor");
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });

        txtArticulo.setForeground(new java.awt.Color(153, 153, 153));
        txtArticulo.setText("Nombre articulo");
        txtArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArticuloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArticuloFocusLost(evt);
            }
        });

        jTxtDescripcion.setColumns(20);
        jTxtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        jTxtDescripcion.setRows(5);
        jTxtDescripcion.setText("Descripcion articulo");
        jTxtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtDescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtDescripcionFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jTxtDescripcion);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria", "Accesorios para Vehículos", "Agro", "Alimentos y Bebidas", "Animales y Mascotas", "Antigüedades y Colecciones", "Arte, Papelería y Mercería", "Bebés", "Belleza y Cuidado Personal", "Boletas para Espectáculos", "Cámaras y Accesorios", "Carros, Motos y Otros", "Celulares y Teléfonos", "Computación", "Consolas y Videojuegos", "Construcción", "Deportes y Fitness", "Electrodomésticos", "Electrónica, Audio y Video", "Herramientas", "Hogar y Muebles", "Industrias y Oficinas", "Inmuebles", "Instrumentos Musicales", "Juegos y Juguetes", "Libros, Revistas y Comics", "Música, Películas y Series", "Recuerdos, Piñatería y Fiestas", "Relojes y Joyas", "Ropa y Accesorios", "Salud y Equipamiento Médico", "Servicios", "Otras categorías" }));

        txtDescuento.setForeground(new java.awt.Color(153, 153, 153));
        txtDescuento.setText("Porcentaje de descuento");
        txtDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusLost(evt);
            }
        });

        checkDescuento.setLabel("¿Tiene Descuento?");
        checkDescuento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkDescuentoItemStateChanged(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtCodigoArticulo.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoArticulo.setText("Codigo articulo");
        txtCodigoArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoArticuloFocusLost(evt);
            }
        });
        txtCodigoArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoArticuloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad)
                    .addComponent(txtValor)
                    .addComponent(txtArticulo)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescuento)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 220, 440));

        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Articulo", "Categoria", "Valor", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableArticulos.setToolTipText("");
        jScrollPane2.setViewportView(jTableArticulos);
        if (jTableArticulos.getColumnModel().getColumnCount() > 0) {
            jTableArticulos.getColumnModel().getColumn(0).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(1).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(2).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(3).setResizable(false);
            jTableArticulos.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 447, 153));

        jLabel4.setText("¿Deseas salir de la cuenta?");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        jLabelRegistrar2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelRegistrar2.setForeground(new java.awt.Color(51, 153, 255));
        jLabelRegistrar2.setText("Salir");
        jLabelRegistrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrar2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabelRegistrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtCodigoArticulo.getText().equals("") || txtCodigoArticulo.getText().equals("Codigo")
                || txtArticulo.getText().equals("") || txtArticulo.getText().equals("Nombre articulo")
                || txtValor.getText().equals("") || txtValor.getText().equals("Valor")
                || txtCantidad.getText().equals("") || txtCantidad.getText().equals("Cantidad")
                || jComboBoxCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String codigo = txtCodigoArticulo.getText();
            String nombreArticulo = txtArticulo.getText();
            String categoria = String.valueOf(jComboBoxCategoria.getSelectedItem());
            String descripcion = "";
            if (!jTxtDescripcion.getText().equals("Descripcion articulo")) {
                descripcion = jTxtDescripcion.getText();
            }
            int cantidad = Integer.parseInt(txtCantidad.getText());
            float valor = Float.parseFloat(txtValor.getText());
            int descuento = 0;
            if (!txtDescuento.getText().equals("Porcentaje de descuento") && !txtDescuento.getText().equals("Porcentaje de descuento")) {
                descuento = Integer.parseInt(txtDescuento.getText());
            }
            Articulo articulo = new Articulo(codigo, nombreArticulo, descripcion, categoria, valor, descuento, cantidad);
            if (controlador.registrarNuevoArticulo(articulo)) {
                limpiarTabla();
                cargar();
                cleanTextField();
                CentroComercial.serializarListaLocales();
                JOptionPane.showMessageDialog(this, "El articulo registrado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "El articulo no pudo ser registrado, verifica que pudo haber fallado :(");
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained
        if (txtCantidad.getText().equals("Cantidad")) {
            txtCantidad.setText("");
            txtCantidad.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCantidadFocusGained

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        if (txtCantidad.getText().equals("")) {
            txtCantidad.setText("Cantidad");
            txtCantidad.setForeground(Color.gray);
        }
        if (!validarNumeros(txtCantidad.getText()) && !txtCantidad.getText().equals("Cantidad")) {
            txtCantidad.setBackground(Color.red);
        } else {
            txtCantidad.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        if (txtValor.getText().equals("Valor")) {
            txtValor.setText("");
            txtValor.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtValorFocusGained

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        if (txtValor.getText().equals("")) {
            txtValor.setText("Valor");
            txtValor.setForeground(Color.gray);
        }
        if (!validarNumeros(txtValor.getText()) && !txtValor.getText().equals("Valor")) {
            txtValor.setBackground(Color.red);
        } else {
            txtValor.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtValorFocusLost

    private void txtArticuloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticuloFocusGained
        if (txtArticulo.getText().equals("Nombre articulo")) {
            txtArticulo.setText("");
            txtArticulo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtArticuloFocusGained

    private void txtArticuloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticuloFocusLost
        if (txtArticulo.getText().equals("")) {
            txtArticulo.setText("Nombre articulo");
            txtArticulo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtArticuloFocusLost

    private void txtDescuentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusGained
        if (txtDescuento.getText().equals("Porcentaje de descuento")) {
            txtDescuento.setText("");
            txtDescuento.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDescuentoFocusGained

    private void txtDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusLost
        if (txtDescuento.getText().equals("")) {
            txtDescuento.setText("Porcentaje de descuento");
            txtDescuento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDescuentoFocusLost

    private void checkDescuentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkDescuentoItemStateChanged
        if (checkDescuento.getState()) {
            txtDescuento.setEnabled(true);
        } else {
            txtDescuento.setEnabled(false);
            txtDescuento.setText("Porcentaje de descuento");
            txtDescuento.setForeground(Color.gray);
        }
    }//GEN-LAST:event_checkDescuentoItemStateChanged

    private void jLabelRegistrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrar2MouseClicked
        VentanaLogIn ventanaLogIn = new VentanaLogIn();
        ventanaLogIn.reinciarLogIn();
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegistrar2MouseClicked

    private void jTxtDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtDescripcionFocusGained
        if (jTxtDescripcion.getText().equals("Descripcion articulo")) {
            jTxtDescripcion.setText("");
            jTxtDescripcion.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTxtDescripcionFocusGained

    private void jTxtDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtDescripcionFocusLost
        if (jTxtDescripcion.getText().equals("")) {
            jTxtDescripcion.setText("Descripcion articulo");
            jTxtDescripcion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTxtDescripcionFocusLost

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtCodigoArticulo.getText().equals("") || txtCodigoArticulo.getText().equals("Codigo")
                || txtArticulo.getText().equals("") || txtArticulo.getText().equals("Nombre articulo")
                || txtValor.getText().equals("") || txtValor.getText().equals("Valor")
                || txtCantidad.getText().equals("") || txtCantidad.getText().equals("Cantidad")
                || jComboBoxCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los datos");
        } else {
            String codigo = txtCodigoArticulo.getText();
            String nombreArticulo = txtArticulo.getText();
            String categoria = String.valueOf(jComboBoxCategoria.getSelectedItem());
            String descripcion = "";
            if (!jTxtDescripcion.getText().equals("Descripcion articulo")) {
                descripcion = jTxtDescripcion.getText();
            }
            int cantidad = Integer.parseInt(txtCantidad.getText());
            float valor = Float.parseFloat(txtValor.getText());
            float descuento = 0;
            if (!txtDescuento.getText().equals("Porcentaje de descuento")) {
                descuento = Float.parseFloat(txtDescuento.getText());
            }
            Articulo articulo = new Articulo(codigo, nombreArticulo, descripcion, categoria, valor, descuento, cantidad);
            if (controlador.modificarArticulo(codigo, articulo)) {
                limpiarTabla();
                cargar();
                cleanTextField();
                JOptionPane.showMessageDialog(this, "El articulo fue modificado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "El articulo no pudo ser modificado, verifica que pudo haber fallado :(");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtCodigoArticulo.getText();
        if (controlador.eliminarArticulo(codigo)) {
            JOptionPane.showMessageDialog(this, "El articulo fue eliminado correctamente");
            limpiarTabla();
            cargar();
            cleanTextField();
        } else {
            JOptionPane.showMessageDialog(this, "El articulo no pudo ser eliminado, verifica que pudo haber fallado :(");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCodigoArticuloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoArticuloFocusLost
        if (txtCodigoArticulo.getText().equals("")) {
            txtCodigoArticulo.setText("Codigo articulo");
            txtCodigoArticulo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCodigoArticuloFocusLost

    private void txtCodigoArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoArticuloMouseClicked
        if (txtCodigoArticulo.getText().equals("Codigo articulo")) {
            txtCodigoArticulo.setText("");
            txtCodigoArticulo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCodigoArticuloMouseClicked

    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9-.]*");
    }

    public static boolean validarLetras(String datos) {
        return datos.matches("[a-zA-Z]*");
    }

    public void cargar() {
        modelo = (DefaultTableModel) jTableArticulos.getModel();
        Object[] ob = new Object[5];
        for (int k = 0; k < negocio.getArticulos().Size(); k++) {
            if (negocio.getArticulos() != null) {
                Articulo arti = negocio.getArticulos().obtenerDato(k);
                ob[0] = arti.getCodigo();
                ob[1] = arti.getNombreProducto();
                ob[2] = arti.getNombreCategoria();
                ob[3] = arti.getValorDelProducto();
                ob[4] = arti.getCantidadProducto();
                modelo.addRow(ob);
            }
        }

        jTableArticulos.setModel(modelo);
    }

    public void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void cleanTextField() {
        txtCodigoArticulo.setText("Codigo articulo");
        txtCodigoArticulo.setForeground(Color.gray);
        txtArticulo.setText("Nombre articulo");
        txtArticulo.setForeground(Color.gray);
        jComboBoxCategoria.setSelectedIndex(0);
        txtValor.setText("Valor");
        txtValor.setForeground(Color.gray);
        txtCantidad.setText("Cantidad");
        txtCantidad.setForeground(Color.gray);
        jTxtDescripcion.setText("Descripcion articulo");
        jTxtDescripcion.setForeground(Color.gray);
        txtCantidad.setText("Cantidad");
        txtCantidad.setForeground(Color.gray);
        txtDescuento.setText("Porcentaje de descuento");
        checkDescuento.setState(false);
        if (checkDescuento.getState()) {
            txtDescuento.setEnabled(true);
        } else {
            txtDescuento.setEnabled(false);
            txtDescuento.setText("Porcentaje de descuento");
            txtDescuento.setForeground(Color.gray);
        }
    }

    public void mouseTablArticulos() {
        jTableArticulos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    txtCodigoArticulo.setText(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 0).toString());
                    txtCodigoArticulo.setForeground(Color.black);
                    txtArticulo.setText(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 1).toString());
                    txtArticulo.setForeground(Color.black);
                    jComboBoxCategoria.setSelectedItem(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 2).toString());
                    txtValor.setText(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 3).toString());
                    txtValor.setForeground(Color.black);
                    txtCantidad.setText(jTableArticulos.getValueAt(jTableArticulos.getSelectedRow(), 4).toString());
                    txtCantidad.setForeground(Color.black);
                    jTxtDescripcion.setText(negocio.buscarArticulo(txtCodigoArticulo.getText()).getDecripcionProducto());
                    jTxtDescripcion.setForeground(Color.black);
                    if (negocio.buscarArticulo(txtCodigoArticulo.getText()).getPorcentajeDescuento() > 0) {
                        checkDescuento.setState(true);
                        txtDescuento.setEnabled(true);
                        txtDescuento.setText(String.valueOf(negocio.buscarArticulo(txtCodigoArticulo.getText()).getPorcentajeDescuento()));
                        txtDescuento.setForeground(Color.black);
                    }
                }
            }
        }
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEncargadoInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEncargadoInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEncargadoInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEncargadoInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private java.awt.Checkbox checkDescuento;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelRegistrar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableArticulos;
    private javax.swing.JTextArea jTxtDescripcion;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoArticulo;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
